// pages/contact.vue
<template>
    <div class="p-2 body">
      <TMeta title="Contact us - TunedStreamz" :url="root + '/contact'" />
      <fieldset class="p-3 br-10 form bg-blue-2 formset border-card">
        <legend class="">Contact us</legend>
        <form action="#" @submit="contactUs">
          <div class="form-group">
            <label for="fullname">Full name:</label>
            <input
              required
              name="name"
              id="fullname"
              type="text"
              class="form-control"
              placeholder="Enter your full name..."
            />
          </div>
          <div class="form-group">
            <label for="email">Email address:</label>
            <input
              reuired
              name="email"
              id="email"
              type="email"
              placeholder="Enter your Email address..."
              class="form-control"
            />
          </div>
          <div class="form-group">
            <label for="msg">Message:</label>
            <textarea placeholder="What is your query?..." required name="message" id="msg" class="form-control" />
          </div>
          <div class="form-group mt-4 mb-3">
            <button class="btn bg-dark-0 m-auto w-100p border-body" type="submit">
              Submit
            </button>
          </div>
        </form>
        <p class="t-c">
          Or email us at:
          <a href="mailto:tunedstreamz@gmail.com" class="link">
            tunedstreamz@gmail.com</a
          >
        </p>
      </fieldset>
    </div>
  </template>

  <script setup lang="ts">
import axios from "axios";
import $ from "jquery"

function contactUs(e: any) {
      e.preventDefault();

      const form = e.currentTarget;
      const btn = $(form.querySelector("button"));
      const { name, email, message } = form;

      const fd = new FormData();
      fd.append("name", name.value);
      fd.append("email", email.value);
      fd.append("message", message.value);
      $(".inProgress").show();
      btn.text("Sending message...");
      btn[0].disabled = true
      axios
        .post(dbUrl + "/contact-us", fd)
        .then((r) => {
          $(".SUCCESS .msg").text("Message sent successfully!");
          $(".SUCCESS").fadeIn();
          btn.text("Success!");
          setTimeout((_) => {
            btn.text("Send message");
            $(".SUCCESS").fadeOut();
          }, 2500);
          $(".inProgress").hide();
          btn[0].disabled = false
        })
        .catch((e) => {
          console.log(e);
          console.log(e.response?.data);
          $(".ERR .msg").text("Something went wrong!");
          $(".ERR").fadeIn();

          setTimeout((_) => $(".ERR").fadeOut(), 2500);
          $(".inProgress").hide();
          btn.text("Retry...");
          btn[0].disabled = false
        });
    }
</script>

// apps/tuheadlines/src/routes/contact/+page.svelte
<script lang="ts">
    import TMeta from "@/components/TMeta.svelte";

    import { api } from "@/lib/api";
    import { SITE } from "@/lib/constants";
    import type { IObj } from "@cmn/utils/interfaces";
    import { page } from "$app/stores";
    import TuLink from "@repo/ui/components/TuLink.svelte";
    import UButton from "@repo/ui/components/UButton.svelte";
    import UForm from "@repo/ui/components/UForm.svelte";
    import UFormGroup from "@repo/ui/components/UFormGroup.svelte";
    import UInput from "@repo/ui/components/UInput.svelte";
    import { handleErrs } from "@cmn/utils/funcs";
    import TuPassField from "@repo/ui/components/TuPassField.svelte";
    import { isTuError } from "@cmn/utils/funcs2";
    import UCheckbox from "@repo/ui/components/UCheckbox.svelte";
    import UTextarea from "@repo/ui/components/UTextarea.svelte";

    let btnDisabled = $state(false),
        setBtnDisabled = (v: boolean) => (btnDisabled = v);
    let passType = $state<"password" | "text">("password"),
        err = $state(""),
        setPassType = (v: typeof passType) => (passType = v),
        setErr = (v: string) => (err = v);

    let formState = $state<IObj>({});

    const submitForm = async (e: any) => {
        e.preventDefault();
        try {
            setErr("");

            const formData = formState;
            const res = await api.post("/message/send", {
                ...formData,
                app: SITE,
                subject: `${SITE} contact us message`
            });
            alert("Message sent successfully");
        } catch (e: any) {
            handleErrs(e);
            const _err = isTuError(e) || "Something went wrong";
            setErr(_err);
        }
    };
</script>

<div class="flex items-center justify-center h-100p w-100p">
    <TMeta title={`Contact us - ${SITE}`} desc="Contact us." />
    <div>
        <UForm state={formState} onsubmit={submitForm} autocomplete="on">
            <fieldset class="formset m-auto border-card border-1 p-4 pb-4">
                <legend class="text-primary text-xl text-cente"
                    ><TuLink to="/">{SITE}</TuLink></legend
                >
                <h2 class="text-cente mb-2 text-center fw-6">Contact us</h2>
                <div class="w-100p flex flex-col gap-2">
                    <UFormGroup label="Full name">
                        <UInput placeholder="e.g John Doe" required name="full-name"/>
                    </UFormGroup>
                    <UFormGroup label="Email address">
                        <UInput
                            style="resize: vertical"
                            placeholder="Enter your email..."
                            required
                            name="email"
                            type="email"
                            bind:value={formState.email}
                        />
                    </UFormGroup>
                    <UFormGroup label="Messege">
                        <UTextarea
                            style="resize: vertical"
                            name="msg"
                            required
                            bind:value={formState.msg}
                            placeholder="Enter message..."
                        />
                    </UFormGroup>
                    {#if err}
                        <div
                            class="ml-2 text-whit fs-12 text-center text-error"
                        >
                            <p>{err?.replace("tu:", "")}</p>
                        </div>
                    {/if}

                    <UFormGroup class="mt-1">
                        <UButton class="w-full btn-primary" type="submit"
                            >Submit</UButton
                        >
                    </UFormGroup>
                </div>
            </fieldset>
        </UForm>
    </div>
</div>
