// apps/tu-trader/apps/tu-trader-sv/src/routes/rf/+page.svelte
<script lang="ts">
    import TMeta from "@/components/TMeta.svelte";
    import TuSelect from "@repo/ui/components/TuSelect.svelte";
    import UButton from "@repo/ui/components/UButton.svelte";
    import UInput from "@repo/ui/components/UInput.svelte";
    import type { ISelectItem } from "@/lib/interfaces";
    import { appStore } from "@/stores/app.svelte";
    import type { IObj } from "@cmn/utils/interfaces";
    import { onMount } from "svelte";
    import { writable } from "svelte/store";
    import type { PageData } from "../$types";
    import CtxMenu2 from "@repo/ui/components/CtxMenu2.svelte";
    import { page } from "$app/stores";

    let {cnt} = appStore
 
    onMount(()=>{
        console.log("Mounted")
        console.log($page.url.searchParams.get("red"))
        setTimeout(()=>{
            
        }, 5000)
        return ()=>{
            console.log("UnMounted")
        }
    })

    let {data} : {data: PageData} = $props()

   

    let opt = $state(1)
    let opts = $state<ISelectItem[]>([{label: "Option 1", value: 1}, {label: 'Option 2', value: 2}])
    onMount(()=>{
        // console.log($path);
        setTimeout(()=>{
            console.log("Update opts");
            opts = [...opts, {label: "Option 3", value: 3}, {label: "Option 4", value: 4, disabled: true}]
            setTimeout(()=>{
                opt = 3
            }, 2000)
        },3000)
    })
    // $inspect(opts)

  let menuOpen = $state(false)
$effect(()=>{
    const rfval = opt
    console.log({rfval});
})
   
</script> 
<TMeta title="RF"/>
<div class="p-4 flex flex-col gap-2" style="width: 500px;">
    <h1>Research Facility</h1>
    <div class="p-2 border-1 border-card rounded-md bg-base-100 w-500px min-h-200px" id="portal">
      <div class="p-2 border-1 border-card">
        <h2>Global state</h2>
        <UButton onclick={_=>{appStore.cnt += 1}}>Counter {appStore.cnt}</UButton>
        <UButton class="btn-primary" loading>Hello fool</UButton>
      </div>
        <TuSelect options={opts} bind:value={opt}/>
        <CtxMenu2 bind:open={menuOpen}>
            {#snippet toggler()}
                <UButton class="btn-primary w-150px">Toggle menu</UButton>
            {/snippet}
            <p>This is menu</p>
        </CtxMenu2>
        <div class="my-3 p-2 border-1 border-card overflow-hidden oy-hidden">
            <div class="flex justify-between">
                <CtxMenu2>
                {#snippet toggler()}
                    <UButton class="btn-secondary">Menu2</UButton>
                {/snippet}
                <p>This is 2nd menu</p>
                <p>This is 2nd menu</p>
                <p>This is 2nd menu</p>
            </CtxMenu2>
            <CtxMenu2>
                {#snippet toggler()}
                    <UButton class="btn-secondary">Menu2</UButton>
                {/snippet}
                <p>This is 2nd menu</p>
                <p>This is 2nd menu</p>
                <p>This is 2nd menu</p>
            </CtxMenu2>
            </div>
            
            <div class="mt-2">
                <h3>Some sub heading</h3>
            </div>
        </div>
        <UInput placeholder="Search here...">
            {#snippet leading()}
                k
            {/snippet}
            {#snippet trailing()}
                S
            {/snippet}
        </UInput>
    </div>
</div>

// apps/tu-next/src/app/rf/page.tsx
"use client";

import LinksComponent from "@/components/LinksComponent";
import { store } from "@/store";
import { getUsers } from "@/utils/server/funcs";

import { sleep } from "@cmn/utils/funcs";
import CtxMenu2 from "@repo/ui-next/components/CtxMenu2";
import TMeta from "@repo/ui-next/components/TMeta";
import TuPaginator from "@repo/ui-next/components/TuPaginator";
import TuSelect from "@repo/ui-next/components/TuSelect";
import UAccordion from "@repo/ui-next/components/UAccordion";
import UButton from "@repo/ui-next/components/UButton";
import UFormGroup from "@repo/ui-next/components/UFormGroup";
import UInput from "@repo/ui-next/components/UInput";
import { useTuState } from "@repo/ui-next/lib/hooks";
import { useTuStore } from "@repo/ui-next/store/utils";

const page = () => {
    const appStore = useTuStore(store.app());
    const selectState = {
        val: useTuState("tonni"),
        options: ["David", "Diaz", "Squash", "Tonni", "Manizo"],
    };

    return (
        <>
            <TMeta title="Tu app mongwaneng" />
            <div className="p-4 border-1 border-card rounded-md w-500px m-auto flex flex-col gap-3">
                <LinksComponent/>
                <CtxMenu2
                    toggler={<UButton className="btn-primary">Toggler</UButton>}
                >
                    <ul>
                        <li className="tu-menu-item">Item 1</li>
                        <li className="tu-menu-item">Item 2</li>
                        <li className="tu-menu-item">Item 3</li>
                    </ul>
                </CtxMenu2>
                <TuSelect
                    value={selectState.val}
                    options={selectState.options.map((el) => ({
                        label: el,
                        value: el.toLowerCase(),
                    }))}
                ></TuSelect>
      
                <UFormGroup label="App name (_state):">
                    <UInput
                        placeholder="Enter app name..."
                        value={appStore.value.title}
                        onChange={({ target }) => {
                            console.log("On change", target.value);
                            appStore.value.title = target.value;
                        }}
                    />
                </UFormGroup>
           
                <UButton
                    onClick={async () => {
                        await sleep(2000);
                        appStore.value.counter += 1;
                    }}
                    className="btn btn-sm btn-secondary"
                >
                    Speed: {appStore.value.counter}
                </UButton>
                <TuPaginator page={useTuState(8)} total={20} />
                <UAccordion label={<h1>Accordion label</h1>}>
                    <div className="p-3">Some accordion content</div>
                </UAccordion>

                <UButton className="btn-secondary" onClick={async ()=>console.log(await getUsers())}>Get users</UButton>
            </div>
        </>
    );
};

export default page;
