// apps/ui-sv/src/components/Loader.svelte
<script lang="ts">
    import {type HTMLAttributes } from "svelte/elements";

    interface IProps extends HTMLAttributes<any>{}
    let {children} : IProps = $props()
</script>
<div class="w-full fixed z-[1000] h-full bg-base-100 flex items-center justify-center tu-loader">
    {#if children}
        {@render children()}
    {:else}
    <div class="loading loading-lg"></div>
    {/if}
</div>
<style>
    .tu-loader{
        top: 0;
        left: 0;

    }
</style>

// apps/ui-next/src/components/Loader.tsx
const loader = ({ children }: { children?: React.ReactNode }) => {
    return (
        <div style={{left: 0, top: 0}} className="w-full fixed z-[1000] h-full bg-base-100 flex items-center justify-center tu-loader">
            {children}
            {children ? children : <div className="loading loading-lg"></div>}
        </div>
    );
};

export default loader;
