// apps/ui/src/components/MenuItem.svelte
<script lang="ts">
    import type { HTMLAttributes } from "svelte/elements";
    import TuLink from "./TuLink.svelte";
    import { onMount } from "svelte";

    let ref: HTMLLIElement | undefined = $state();
    interface IProps extends HTMLAttributes<any> {
        to?: string;
        title?: string;
        innerClass?: string;
        icon?: string;
        reload?: boolean;
        loading?: boolean;
        disabled?: boolean;
    }
    let {
        to,
        innerClass,
        children,
        title,
        icon,
        reload,
        class: _class,
        onclick,
        loading = $bindable(),
        disabled,
        ...props
    }: IProps = $props();

    $effect(() => {
        // console.log({onclick});
        onclick;
        ref.onclick = async (e) => {
            loading = true;
            try {
                await onclick(e);
            } catch (err) {
                console.log(err);
            } finally {
                loading = false;
            }
        };
    });
</script>

<li
    bind:this={ref}
    class={`tooltip tooltip-right tu-menu-item ${(loading || disabled) && "disabled"} ` +
        _class}
    data-tip={title}
    {...props}
>
    {#if to}
        <TuLink {reload} {to} class={`flex items-center gap-2 ${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            <div class="flex-1">
                {@render children?.()}
            </div>
            {#if loading}
                <span class="loading loading-sm loading-ring"></span>
            {/if}
        </TuLink>
    {:else}
        <span class={`flex items-center gap-2 ${innerClass}`}>
            {#if icon}
                <i class={icon}></i>
            {/if}
            <div class="flex-1">
                {@render children?.()}
            </div>
            {#if loading}
                <span class="loading loading-sm loading-ring"></span>
            {/if}
        </span>
    {/if}
</li>

// apps/ui-next/src/components/MenuItem.tsx
import { HTMLAttributes, useEffect, useRef } from "react";
import { TState } from "../lib/interfaces";
import TuLink from "./TuLink";

interface IProps extends HTMLAttributes<any> {
    to?: string;
    title?: string;
    innerClass?: string;
    icon?: string;
    reload?: boolean;
    loading?: TState<boolean>;
    disabled?: boolean;
}
const MenuItem = ({
    to,
    innerClass,
    children,
    title,
    icon,
    reload,
    className,
    onClick,
    loading,
    disabled,
    ...props
}: IProps) => {

    const ref = useRef<HTMLLIElement>(null)
    useEffect(()=>{
        ref.current.onclick = async (e) => {
            loading.value = true;
            try {
                await onClick(e as any);
            } catch (err) {
                console.log(err);
            } finally {
                loading.value = false;
            }
        };
    }, [onClick])
    const Child = () => (
        <>
            {icon && <i className={icon}></i>}
            <div className="flex-1">{children}</div>
            {loading.value && (
                <span className="loading loading-sm loading-ring"></span>
            )}
        </>
    );
    return (
        <li
            ref={ref}
            className={
                `tooltip tooltip-right tu-menu-item ${(loading.value || disabled) && "disabled"} ` +
                className
            }
            data-tip={title}
            {...props}
        >
            {to ? (
                <TuLink
                    reload={reload}
                    to={to}
                    className={`flex items-center gap-2 ${innerClass}`}
                >
                    <Child />
                </TuLink>
            ) : (
                <span className={`flex items-center gap-2 ${innerClass}`}>
                    <Child />
                </span>
            )}
        </li>
    );
};

export default MenuItem;
