// apps/ui-sv/src/components/TuErrorPage.svelte
<div class="tu-error-page">
    <div class="error">
        <span class="status">{page.status}</span>
        <div class="message">
            <h1>{page.error.message.replaceAll("tu:", "")}</h1>
        </div>
    </div>
</div>

<script lang="ts">
    import {page} from "$app/state"
</script>
<style lang="scss">

 
</style>

// apps/ui-next/src/components/TuErrorPage.tsx
import TMeta from "./TMeta";

export default function TuErrorPage({
    status,
    msg,
}: {
    status: number;
    msg: string;
}) {
    return (
        <>
        <TMeta title={`${status}: ${msg}`}/>
        <div className="tu-error-page">
            <div className="error">
                <span className="status">{status}</span>
                <div className="message">
                    <h1>{msg}</h1>
                </div>
            </div>
        </div></>
        
    );
}
