// apps/ui/src/components/TuTabItem.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    interface IProps {
        tab: number;
        i: number;
        label: Snippet;
        content: Snippet;
    }
    let { tab = $bindable(), i, content, label }: IProps = $props();
</script>

<a href="#" role="tab" class={`tab ${tab == i && 'tab-active'}`} onclick={_=> tab = i}>{@render label()}</a>
{#if tab == i}
    <div class="tu-tab-content">
        {@render content()}
    </div>
{/if}

// apps/ui-next/src/components/TuTabItem.tsx
import { TState } from "../lib/interfaces";
import { useTuState } from "../lib/tu";

interface IProps {
    tab: TState<number>;
    i: number;
    label: React.ReactNode;
    content: React.ReactNode;
}
const TuTabItem = ({ tab = useTuState(0), i, content, label }: IProps) => {
    return (
        <>
            <a
                href="#"
                role="tab"
                className={`tab ${tab.value == i && "tab-active"}`}
                onClick={(_) => (tab.value = i)}
            >
                {label}
            </a>
            {tab.value == i && <div className="tu-tab-content">{content}</div>}
        </>
    );
};

export default TuTabItem;
