// apps/ui-sv/src/components/TuTeleport.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
  
    export let to = 'body';
  
    let element: HTMLDivElement;
  
    onMount(() => {
      const targetElement = document.querySelector(to);
      if (targetElement) {
        targetElement.appendChild(element);
        element.classList.remove('hidden')
      }
    });
  
    onDestroy(() => {
      element?.remove();
    });
  </script>
  
  <div bind:this={element} class="hidden">
    <slot></slot>
  </div>

// apps/ui-next/src/components/TuTeleport.tsx
import { useEffect, useRef } from "react";

interface IProps {
    to?: string; children?: React.ReactNode
}
const TuTeleport = ({ to = "body", children, ...props }: IProps) => {
    const element = useRef<HTMLDivElement>(null);
    useEffect(() => {
        const targetElement = document.querySelector(to);
        if (targetElement) {
            targetElement.appendChild(element.current);
            element.current.classList.remove("hidden");
        }
        return () => {
            // element.current?.remove();
        };
    });
    return (
        <div ref={element} className="hidden">
            {children}
        </div>
    );
};

export default TuTeleport;
