// apps/ui/src/components/UCheckbox.svelte

    <UFormGroup class={"text-center flex items-end fs-15 gap-1.5 justify-end mt-1 " + _class} style="flex-direction: row-reverse; width: fit-content" labelClass="!mb-0" {...props} labelStyle="line-height: 1rem">
        <input
            
            disabled={disabled}
            type="checkbox"
            class={toggle ? "toggle": "checkbox checkbox-xs checkbox-primary border-card"}
            bind:checked={value}
        />
    </UFormGroup>

<script lang="ts">
    import UFormGroup from "./UFormGroup.svelte";

    let {disabled, toggle,value = $bindable(), class: _class,...props}: {disabled?: boolean, value?: boolean; [key: string]: any; toggle?: boolean} = $props()
</script>

// apps/ui-next/src/components/UCheckbox.tsx
import { TState } from "../lib/interfaces";
import { useTuState } from "../lib/tu";
import UFormGroup from "./UFormGroup";

const UCheckbox = ({
    disabled,
    toggle,
    value = useTuState(),
    className,
    ...props
}: {
    disabled?: boolean;
    value?: TState<boolean>;
    [key: string]: any;
    toggle?: boolean;
}) => {
    return ( <UFormGroup
        className={"text-center flex items-end fs-15 gap-1.5 justify-end mt-1 " +
            className}
        style={{flexDirection: 'row-reverse', width: 'fit-content'}}
        labelClass="!mb-0"
        {...props}
        labelStyle={{lineHeight: '1rem'}}
    >
        <input
            disabled={disabled}
            type="checkbox"
            className={toggle
                ? "toggle"
                : "checkbox checkbox-xs checkbox-primary border-card"}
            checked={value.value}
            onChange={e=> value.value = e.target.checked}
        />
    </UFormGroup> );
}
 
export default UCheckbox;
