// apps/ui/src/components/UInput.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLInputAttributes } from "svelte/elements";

    export interface IUInputProps extends HTMLInputAttributes {
        value?: any;
        override?: string;
        inputClass?: string;
        trailing?: Snippet;
        leading?: Snippet;
    }

    let {
        override = "",
        value = $bindable(),
        class: _class,
        trailing,
        leading, inputClass,
        ...props
    }: IUInputProps = $props();
    const defClass = override.split(" ").find((el) => el == "class")
        ? ""
        : "flex gap-3 items-center input input-bordered input-sm ";
</script>

<div class={defClass + _class || ''}>
    {@render leading?.()}
    <input autocomplete="on" bind:value {...props} class={inputClass || ''} />
    {@render trailing?.()}
</div>

<style lang="scss">
    .input {
        display: flex;
        flex-direction: row;
        gap: 4px;
        align-items: center;
        .trailing {
            align-self: flex-end;
        }
    }
</style>

// apps/ui-next/src/components/UInput.tsx
import { InputHTMLAttributes, ReactNode } from "react";

export interface IUInputProps extends InputHTMLAttributes<any> {
    override?: string;
    inputClass?: string;
    trailing?: ReactNode;
    leading?: ReactNode;
}
const UInput = ({value, disabled, inputClass,leading, trailing, className,override,...props}: IUInputProps) => {
    const defClass = override && override.split(" ").find((el) => el == "class")
        ? ""
        : "flex gap-3 items-center input input-bordered input-sm ";
    return ( <div className={`${defClass + className || ''} ${disabled && 'disabled'}`}>
        {leading}
        <input value={value} {...props} className={inputClass || ''} disabled={disabled} />
        {trailing}
    </div>
  
     );
}
 
export default UInput;
