// apps/ui-sv/src/components/UTextarea.svelte
<script lang="ts">
    import type { HTMLTextareaAttributes } from "svelte/elements";
    interface IProps extends HTMLTextareaAttributes {value?: any}
    let {value = $bindable() , class: _class,...props }: IProps = $props();
</script>

<textarea bind:value={value} style="resize: both;" class={"textarea textarea-bordered " + _class} {...props}
></textarea>

// apps/ui-next/src/components/UTextarea.tsx
import { TextareaHTMLAttributes } from "react";
import { useTuState } from "../lib/tu";

interface IProps extends TextareaHTMLAttributes<{}> {
    value?: any;
}

const UTextArea = ({ value = useTuState(), className, ...props }: IProps) => {
    return (
        <textarea
            value={value.value}
            onChange={({ target }) => (value.value = target.value)}
            style={{ resize: "both" }}
            className={"textarea textarea-bordered " + className}
            {...props}
        ></textarea>
    );
};

export default UTextArea;
