// apps/tu-next/src/app/rf/page.tsx
"use client";

import ReduxComp from "@/components/rf/ReduxComp";
import TMeta from "@repo/ui-next/components/TMeta";



const page = () => {

    return (
        <>
            <TMeta title="Research Facility"/>
            <div className="p-4 flex flex-col w-full h-full gap-3">
                <ReduxComp/>
            </div>
        </>
    );
};

export default page;

// apps/tstreamz/apps/frontend/src/routes/rf/+page.svelte
<script>
    
    import PellerPopunder from "@/components/PellerPopunder.svelte";
    import PellerPush from "@/components/PellerPush.svelte";
import TMeta from "@/components/TMeta.svelte";
    import { SITE } from "@/lib/constants";
    import UButton from "@repo/ui/components/UButton.svelte";

</script>
<TMeta title={`Research Facility - ${SITE}`}/>
<UButton/>
<div class="p-4">
    <h1 class="title">RF</h1>
    <PellerPopunder/>
    <PellerPush/>
</div>
