// pages/discover/star/[id].vue
<template>
    <div>
    <TMeta
      v-if="star"
      :title="'Discover movies with ' + star?.name + ' - TunedStreamz'"
      :desc="`Discover some of the best movies with ${star?.name}.`"
      :url="root + `/discover/star/${star?.id}`"
      :src="imgUrl + star?.profile_path"
    />

    
    <div v-if="movies"><section>
      <h3 class="text-center">
        Movies with <span class="color-orange">{{ star?.name }}</span>
      </h3>
    </section>
    <section v-if="movies" style="margin-top: -20" class="">
      <div >
        <FixedMovieCard :movies="movies" :wrap="true" />
      </div>
    </section></div>

    <div
      @touchmove="(e) => e.preventDefault()"
      @wheel="(e) => e.preventDefault()"
      v-else
      class="d-flex ai-center jc-center loda"
    >
      <p class="fs-40"><b>Loading....</b></p>
    </div>
  </div>
</template>
<script setup lang="ts">

import { ref, onBeforeMount } from "vue";
import {imgUrl, root} from '@/utils/constants'

const route = useRoute();
  const id = ref(route.params.id);
  const movies = ref<[any]>(), star = ref<any>();

const { data, error} = await useFetch<any>('/api/discover/star/' + id.value, {
    watch: [id]
})
if (error.value) {
  throw createError({ statusCode: error.value?.statusCode, statusMessage: error.value.statusMessage });
}
movies.value = data.value.data.movies
star.value = data.value.data.star

</script>

// apps/tstreamz/apps/frontend/src/routes/discover/star/[id]/+page.svelte
<script lang="ts">
    import { imgUrl, ROOT, SITE } from "@/lib/constants";
    import { preventScroll } from "@/lib/funcs";
    import FixedMovieCard from "@/components/FixedMovieCard.svelte";
    import TMeta from "@/components/TMeta.svelte";
    import Loader from "@repo/ui/components/Loader.svelte";
    import { onMount } from "svelte";

    let movies = $state<[any]>(),
        star = $state<any>();

    const { data } = $props();

    onMount(() => {
        movies = data.movies;
        star = data.star;
    });
</script>

{#if star}
    <div>
        <TMeta
            title={"Discover movies with " + star?.name + " - " + SITE}
            desc={`Discover some of the best movies with ${star?.name}.`}
            url={ROOT + `/discover/star/${star?.id}`}
            src={imgUrl + star?.profile_path}
        />

        {#if movies}
            <div class="pdy-4">
                <section class="mb-4"><div
                        style="flex-shrink: 0"
                        class="w-150px h-150px pos-rel pd-2 border-1 border-card br-4 m-auto bg-base-200"
                    >
                        <img
                            alt="Movie  banner"
                            loading="lazy"
                            class="br-4"
                            width="100%"
                            height="auto"
                            src={imgUrl + star?.profile_path}
                        />
                    </div>
                    <h3 class="text-center text-white fs-18">
                        Movies with <span class="text-primary"
                            >{star?.name}</span
                        >
                    </h3>
                    
                </section>

                <section style="margin-top: -20" class="">
                    <div>
                        <FixedMovieCard {movies} wrap />
                    </div>
                </section>
            </div>
        {:else}
            <div
                ontouchmove={preventScroll}
                onwheel={preventScroll}
                class="d-flex ai-center jc-center loda"
            >
                <p class="fs-40"><span class="loading loading-lg"></span></p>
            </div>
        {/if}
    </div>
{:else}
    <Loader />
{/if}
