// apps/tstreamz/apps/frontend/src/components/FixedMovieCard.svelte
<script lang="ts">
    import { imgUrl } from "@/lib/constants";
    import type { IObj } from "@cmn/utils/interfaces";
    import TuLink from "@repo/ui/components/TuLink.svelte";
    import { untrack } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";
    import WatchlistBtn from "./WatchlistBtn.svelte";

    interface IProps extends HTMLAttributes<any> {
        name?: string;
        movies: IObj[];
        wrap?: boolean;
        isShow?: boolean;
    }

    const {
        name,
        movies,
        wrap,
        isShow,
        class: _class,
        ...props
    }: IProps = $props();

    let classes = $state(""),
        cardClasses = $state("");

    $effect(() => {
        // watch wrap
        const v = wrap;
        untrack(() => {
            classes = v ? "row items-center justify-center" : "flex no-wrap items-center";
            cardClasses = v ? "row items-center" : "flex no-wrap items-center";
        });
    });
</script>

<div class={`${classes} ${_class} gap-2 overflow-x-scroll`} {...props}>
    {#each movies as it, i}
        <div title={isShow ? it.name : it.title} class="fmc fshr-0 p-0 oh">
            <div class="movie-card h-100p bg-card">
                <div class="w-100p h-130px pos-rel">
                    <div
                        style="background-size: cover"
                        class="br-4 pos-rel w-100p h-100p"
                    >
                        <img
                            alt="movie cover"
                            class="br-4 w-100p"
                            loading="lazy"
                            src={imgUrl + it.poster_path}
                        />
                    </div>
                    <div class="info flex items-center justify-center pos-abs w-100p h-100p">
                        <TuLink
                            class="playBtn btn-none fs-30"
                            to={`/watch/${isShow ? "tv" : "m"}/${it.id}`}
                            ><i class="fi fi-rr-play"></i></TuLink
                        >
                    </div>
                </div>
                <div class="oh" style="padding: 0px">
                    <div>
                        <div class="flex justify-between items-center">
                            <TuLink
                                class="fs-13 wp-nowrap text-ellipsis"
                                to={`/watch/${isShow ? "tv" : "m"}/${it.id}`}
                                ><h3 class="fs-14 text-white wp-nowrap text-ellipsis">
                                    {isShow ? it.name : it.title}
                                </h3></TuLink
                            >
                            <WatchlistBtn {isShow} item={it} />
                        </div>
                        <div class="flex fs-12 justify-between">
                            <div>
                                <span><i class="fal fa-calendar"></i></span
                                >&nbsp;{isShow
                                    ? it?.first_air_date?.split("-")[0]
                                    : it?.release_date?.split("-")[0]}
                            </div>
                            <div>
                                <span class="color-yellow"
                                    ><i class="fi fi-ss-star"
                                    ></i>&nbsp;{Number(it.vote_average).toFixed(1)}</span
                                >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {/each}
</div>

// components/FixedMovieCard.vue
<template>
  <div class="row no-wrap ai-center">
    <div :key="i" v-for="(it, i) in movies" :title="isShow ? it.name : it.title" class="fmc fshr-0 p-0 oh">
      <div class="movie-card fixed h-100p bg-card oh">
        <div class="w-100p h-130 pos-rel">
          <div
            :style="`background-size: cover`"
            class="br-4 pos-rel w-100p h-100p"
          >
            <img alt="Movie cover" class='br-4' loading="lazy" :src="imgUrl + it.poster_path" />
          </div>
          <div class="info dflex jc-center pos-abs w-100p h-100p">
            <NuxtLink
              class="playBtn btn-none"
              :to="`/watch/${isShow ? 'tv' : 'm'}/${it.id}`"
              ><i class="fal fa-play-circle"></i
            ></NuxtLink>
          </div>
        </div>
        <div class="oh " style="padding: 0px">
        <div>
          <div class="d-flex jc-sb ai-center">
            <NuxtLink
              class="fs-13 w-nowrap"
              :to="`/watch/${isShow ? 'tv' : 'm'}/${it.id}`"
              ><h3 class="fs-14 color-white w-nowrap">
                {{ isShow ? it.name : it.title }}
              </h3></NuxtLink
            >
            <WatchlistBtn :isShow="isShow" :item="it" />
          </div>
          <div class="d-flex fs-12 jc-sb">
            <div>
              <span><i class="fal fa-calendar"></i></span>&nbsp;{{
                isShow
                  ? it?.first_air_date?.split("-")[0]
                  : it?.release_date?.split("-")[0]
              }}
            </div>
            <div>
              <span class="color-yellow"
                ><i class="fas fa-star"></i>&nbsp;{{ it.vote_average }}</span
              >
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { imgUrl } from "@/utils/constants";
defineProps({
    name: {
        type: String
    },
    movies: {
        type: Array<any>
    },
    isShow: {
        type: Boolean
    }
})
</script>
