// apps/tstreamz/apps/frontend/src/components/WatchlistBtn.svelte
<script lang="ts">
    import { localApi } from "@/lib/api";
    import { appStore } from "@/stores/app.svelte";
    import { setWatchlist, userStore } from "@/stores/user.svelte";
    import type { IObj } from "@cmn/utils/interfaces";

    import UButton from "@repo/ui/components/UButton.svelte";
    import type { HTMLAttributes } from "svelte/elements";

    let progress = $state(false);

    let { ready } = $derived(appStore);
    let { user, watchlist } = $derived(userStore);

    interface IProps extends HTMLAttributes<any> {
        isShow?: boolean;
        item: IObj;
    }
    const { isShow, item, class: _class, ...props }: IProps = $props();

    function addToList() {
        progress = true;
        const inte = setInterval(() => {
            if (ready) {
                clearInterval(inte);
                next();
            }
        }, 1000);

        const next = () => {
            if (!user?.username) {
                alert("Please login or signup to add movies to your watchlist");
                progress = false;
                return;
            }

            let newList = [];
            if (
                (isShow && watchlist?.shows) ||
                (!isShow && watchlist?.movies)
            ) {
                newList = isShow
                    ? [...watchlist.shows, item]
                    : [...watchlist.movies, item];
            } else {
                newList = [item];
            }
            const newWList = isShow
                ? { ...watchlist, shows: newList }
                : { ...watchlist, movies: newList };
            const fd = new FormData();
            fd.append("watchlist", JSON.stringify(newWList));
            localApi
                .post("/user/watchlist", fd)
                .then((res) => {
                    setWatchlist(newWList);

                    alert(
                        isShow
                            ? "Series added to watchlist"
                            : "Movie added to watchlist"
                    );
                    progress = false;
                })
                .catch((err) => {
                    alert("Could not add to watchlist");
                    console.log(err);
                    progress = false;
                });
        };
        //progress = false;
    }
    function rmvFromList() {
        progress = true;
        let newList = [];
        if (watchlist) {
            newList = isShow
                ? watchlist.shows.filter((it: any) => it?.id !== item?.id)
                : watchlist.movies.filter((it: any) => it?.id !== item?.id);
        }
        const newWList = isShow
            ? { ...watchlist, shows: newList }
            : { ...watchlist, movies: newList };

        const fd = new FormData();
        fd.append("watchlist", JSON.stringify(newWList));
        localApi
            .post("/user/watchlist", fd)
            .then((res) => {
                setWatchlist(newWList);

                alert(
                    isShow
                        ? "Series removed from watchlist"
                        : "Movie removed from watchlist"
                );
                progress = false;
            })
            .catch((err) => {
                alert("Could not add to watchlist");
                console.log(err);
                progress = false;
            });
    }
</script>

<div class={`${_class}`} {...props}>
    {#if !(isShow ? watchlist?.shows : watchlist?.movies)?.find((it: any) => it?.id === item?.id)}
        <UButton
            onclick={addToList}
            title="Add to watchlist"
            class="btn-none fs-14 wlst-btn btn-outline"
            disabled={progress}
        >
            <i class="fi fi-br-bookmark"></i>
        </UButton>
    {:else}
        <UButton
            onclick={rmvFromList}
            title="Remove from watchlist"
            class="btn-none color-orange fs-14 wlst-btn btn-outline"
            disabled={progress}
        >
            <i class="fi fi-sr-bookmark"></i>
        </UButton>
    {/if}
</div>

<style>
</style>

// components/WatchlistBtn.vue
<template>
    <div>
      <button
        @click="addToList"
        title="Add to watchlist"
        v-if="
          !(isShow ? appStore.watchlist?.shows :appStore. watchlist?.movies)?.find(
            (it: any) => it?.id === item?.id
          )
        "
        class="btn-none fs-18 wlst-btn"
        :disabled="progress"
      >
        <i class="far fa-bookmark"></i>
      </button>
      <button
        @click="rmvFromList"
        title="Remove from watchlist"
        v-else
        class="btn-none color-orange fs-18 wlst-btn"
        :disabled="progress"
      >
        <i class="fas fa-bookmark"></i>
      </button>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref } from "vue";
  import { post } from "@/utils/api";
import { useAppStore } from "@/stores/app";
import {storeToRefs} from 'pinia'

  const progress = ref(false);

  const appStore = useAppStore()
const  { user, watchlist, ready} = storeToRefs(appStore)

  const props = defineProps({
    isShow: {type: Boolean},
    item : {type: Object}
  })


  function addToList() {
      progress.value = true;
      const inte = setInterval(() => {
        if (ready.value) {
          clearInterval(inte);
          next();
        }
      }, 1000);

      const next = () => {
        if (!user.value?.username) {
          alert("Please login or signup to add movies to your watchlist");
          progress.value = false;
          return;
        }

        let newList = [];
        const {isShow, item} = props
        if ((isShow && watchlist.value?.shows) || (!isShow && watchlist.value?.movies)) {
          newList = isShow
            ? [...watchlist.value.shows, item]
            : [...watchlist.value.movies, item];
        } else {
          newList = [item];
        }
        const newWList = isShow
          ? { ...watchlist.value, shows: newList }
          : { ...watchlist.value, movies: newList };
        const fd = new FormData();
        fd.append("watchlist", JSON.stringify(newWList));
        post("/user/watchlist", fd)
          .then((res) => {
            appStore.setWatchlist(newWList);

            alert(
              isShow ? "Series added to watchlist" : "Movie added to watchlist"
            );
            progress.value = false;
          })
          .catch((err) => {
            alert("Could not add to watchlist");
            console.log(err);
            progress.value = false;
          });
      };
      //progress.value = false;
    }
    function rmvFromList() {
   
      const { isShow, item } = props;
         progress.value = true;
      let newList = [];
      if (watchlist) {
        newList = isShow
          ? watchlist.value.shows.filter((it : any) => it?.id !== item?.id)
          : watchlist.value.movies.filter((it : any) => it?.id !== item?.id);
      }
      const newWList = isShow
        ? { ...watchlist.value, shows: newList }
        : { ...watchlist.value, movies: newList };

      const fd = new FormData();
      fd.append("watchlist", JSON.stringify(newWList));
      post("/user/watchlist", fd)
        .then((res) => {
         appStore. setWatchlist(newWList);

          alert(
            isShow
              ? "Series removed from watchlist"
              : "Movie removed from watchlist"
          );
          progress.value = false;
        })
        .catch((err) => {
          alert("Could not add to watchlist");
          console.log(err);
          progress.value = false;
        });
    }
  </script>
  <style>
 
  </style>
