// apps/ui-next/src/components/TuModal.tsx
import { useEffect } from "react";
import { useTuState } from "../lib/tu";
import { TState } from "../lib/interfaces";
import TuTeleport from "./TuTeleport";
import TuModalContainer from "./TuModalContainer";

const TuModal = ({
    open = useTuState(false),
    content,
    toggler,
    className,
}: {
    open?: TState<boolean>;
    content?: React.ReactNode;
    toggler?: React.ReactNode;
    className?: string;
}) => {
    const id = useTuState("");
    useEffect(() => {
        id.value = `modal-${Date.now()}`;
    }, []);
    return (
        <div>
            <label
                htmlFor={id.value}
                onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    open.value = true;
                }}
            >
                {toggler}
            </label>

            <TuTeleport to="#ctx-overlay">
                <div
                    className={`modal modal-md flex-col flex items-center justify-center ${open.value ? "modal-open" : ""}`}
                >
                    <TuModalContainer open={open} blank>
                        {open.value && (
                            <div className={"modal-box min-w-400 " + className}>
                                {content}
                            </div>
                        )}
                    </TuModalContainer>

                    <label className="modal-backdrop" htmlFor={id.value}>
                        Close
                    </label>
                </div>
            </TuTeleport>
            <input className="checkbox hidden" type="checkbox" />
        </div>
    );
};

export default TuModal;

// apps/ui/src/components/TuModal.svelte
<script lang="ts">
    import { onMount, type Snippet } from "svelte";
    import TuModalContainer from "./TuModalContainer.svelte";
    import TuTeleport from "./TuTeleport.svelte";

    let id = $state("");
    let { open = $bindable(false), content, toggler }: { open?: boolean; content?: Snippet; toggler?: Snippet } = $props();

    onMount(() => {
        id = `modal-${Date.now()}`;
    });
</script>

<div>
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <label
        for={id}
        onclick={(e) => {
            e.preventDefault();
            e.stopPropagation();
            open = true;
        }}
    >
        {@render toggler?.()}
    </label>

    <!-- Put this part before </body> tag -->
    <TuTeleport to="#ctx-overlay">
        <div class={`modal modal-md flex-col flex items-center justify-center ${open ? "modal-open" : ""}`}>
            <TuModalContainer bind:open={open} blank>
                {#if open}
                   <div class="modal-box min-w-400">
                    {@render content?.()}
                </div> 
                {/if}
                
            </TuModalContainer>

            <label class="modal-backdrop" for={id}>Close</label>
        </div></TuTeleport
    >
    <input class="checkbox hidden" type="checkbox" />
</div>
