// apps/ui-next/src/components/UAccordion.tsx
import { DetailsHTMLAttributes } from "react";

interface IProps extends Omit<DetailsHTMLAttributes<{}>, "content"> {
    label?: React.ReactNode;
    content?: React.ReactNode;
    multiple?: boolean;
}
const UAccordion = ({
    label,
    content,
    className,
    multiple,
    ...props
}: IProps) => {
    return (
        <details
            className={
                "collapse collapse-arrow border border-card  collapse-sm hdn " +
                className
            }
            {...props}
        >
            <summary className="collapse-title text-l font-medium w-full">
                {label}
            </summary>
            <div className="collapse-content w-full">{content}</div>
        </details>
    );
};

export default UAccordion;

// apps/ui/src/components/UAccordion.svelte
    <details class={"collapse collapse-arrow border border-card  collapse-sm hdn " + _class} {...props}>
        <summary class="collapse-title text-l font-medium">
            {@render label?.()}
        </summary>
        <div class="collapse-content">
            {@render content?.()}
        </div>
    </details>

<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLDetailsAttributes } from "svelte/elements";

    interface IProps extends HTMLDetailsAttributes{label?: Snippet; content?: Snippet; multiple?: boolean}
    const {label, content, class: _class, multiple, ...props} : IProps = $props()
</script>
<style>
</style>
