// apps/ui-next/src/components/UAvatar.tsx
import { HTMLAttributes } from "react";

interface IProps extends HTMLAttributes<any> {
    online?: boolean;
    innerclass?: string;
}
const UAvatar = ({ online, children, className, ...props }: IProps) => {
    return (
        <div
            className={`avatar ring rounded-full w-25px h-25px flex items-center justify-center ring-offset-base-100 ring-offset-2 ${online != undefined ? (online ? "online" : "offline") : ""} ${className}`}
            {...props}
        >
            {children}
        </div>
    );
};

export default UAvatar;

// apps/ui/src/components/UAvatar.svelte

    <div class={`avatar ring rounded-full ring-primary w-25px h-25px flex items-center justify-center ring-offset-base-100 ring-offset-2 ${online != undefined ? (online ? 'online' : 'offline') : ''} ${_class}`} {...props}>

      {@render children?.()}
    </div>


<script lang="ts">
    import type { HTMLAttributes } from "svelte/elements";


    interface IProps extends HTMLAttributes<any>{online?: boolean; innerclass?: string}
const {online, children, class: _class, ...props} : IProps = $props()
</script>
