// apps/ui-next/src/components/UFormGroup.tsx
import { IObj } from "@cmn/utils/interfaces";
import { LabelHTMLAttributes, ReactNode } from "react";

interface IProps extends LabelHTMLAttributes<{}> {
    label?: ReactNode | string;
    labelClass?: string;
    labelStyle?: IObj;
}

const UFormGroup = ({
    label,
    labelClass = "",
    children,
    className,
    labelStyle,
    ...props
}: IProps) => {
    return (
        <label className={"label block " + className} {...props}>
            <div className={`mb-1 ml-1 ${labelClass}`} style={labelStyle}>
                {label}
            </div>
            {children}
        </label>
    );
};

export default UFormGroup;

// apps/ui/src/components/UFormGroup.svelte
    <label class={"label block " + _class} {...props}
        >
        <div class={`mb-1 ml-1 ${labelClass}`} style={labelStyle}>
            {#if typeof label == 'string'}
                {label}
            {:else}
            {@render label?.()}
            {/if}
        </div>
        {@render children?.()}
    </label>

<script lang="ts">
    import type { Snippet } from "svelte";
    import type{ HTMLLabelAttributes} from 'svelte/elements'

interface IProps extends HTMLLabelAttributes {label?: Snippet | string; labelClass?: string; labelStyle?: string }

let {label, labelClass= "", children, class: _class, labelStyle, ...props}: IProps = $props()
</script>
