// apps/tstreamz/apps/frontend/src/routes/auth/signup/+page.svelte
<script lang="ts">
    import type { IObj } from "@cmn/utils/interfaces";
    import { onMount } from "svelte";
    import jq from "jquery"
    import { localApi } from "@/lib/api";
    import { setUser } from "@/stores/user.svelte";
    import { SITE, STORAGE_KEYS } from "@/lib/constants";
    import UInput from "@repo/ui/components/UInput.svelte";
    import TuLink from "@repo/ui/components/TuLink.svelte";
    import UButton from "@repo/ui/components/UButton.svelte";
    import UForm from "@repo/ui/components/UForm.svelte";
    import TMeta from "@/components/TMeta.svelte";
    import UFormGroup from "@repo/ui/components/UFormGroup.svelte";
    import { handleErrs } from "@cmn/utils/funcs";
    let pwd = $state("")
    let btnDisabled = $state(true),
        passType = $state<"text" | "password">("password"),
        err = $state(""),
        formData = $state<IObj>({}),
            step = $state(0);
            const passPattern = /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}/
    let formRef: HTMLDivElement;

    const submitOTP = async (e:any) => { 
        e.preventDefault()
        const form = e.target
        const btn: HTMLButtonElement = form.querySelector('button[type="submit"]')
        try{
            btn.textContent = "..."
            err = ("")
            btnDisabled = (true) 
            const res = await localApi.post('/auth/verify-email', formData)
            const { user, token} = res.data

            setUser(user)
            localStorage.setItem(STORAGE_KEYS.authTkn, token)

            setTimeout(()=>{btnDisabled = (false)}, 1500)
            location.href = "/"
        }catch(e: any){
            console.log(e)
            const _err = e.response?.data?.startsWith("tuned:") ? e.response.data.replace("tuned:", "") : "Something went wrong"
            err = (_err)
            btn.textContent = "Retry"
            btnDisabled = (false)
        }
     }

     const validClass = "text-primary", invalidClass = "text-error"

     const submitForm = async (e:any)=>{
        try {
                // btnDisabled = (true);
                const form = e.target
                err = ("");
                console.log("Signing up...");
                jq("#su-btn").text("Signing up...");
                let password = form["password"].value;
                let email = form["email"].value;
                let username = form["username"].value;
                formData = ({...formData, email})
                let fd = { password, email, username };
                localApi.post("/auth/signup?method=custom", fd)
                    .then((res) => {
                        jq(".inProgress").hide();
                        err = ("");
                        jq(".su-btn").text("Successful!");
                        const { id } = res.data;
                        console.log(id);
                        btnDisabled = (false);
                        step = (1)
                    })
                    .catch((er: any) => {
                        handleErrs(er)
                        jq(".inProgress").hide();
                        let error = er.response?.data;
                        jq(".su-btn").text("Retry");

                        // err = error?.startsWith('tu:') ? error.replace('tu:', '') : 'Something went wrong'
                        btnDisabled = (false);
                    });
            } catch (e) {
                handleErrs(e);
                // btnDisabled = (false);
                jq("#su-btn").text("Error! Retry...");
            }
     }
    onMount(()=>{
        const form = formRef?.querySelector('form');
        if (!form) return;
        let pass: HTMLInputElement = form.querySelector("#pass")!;

        const pwdInp = form["password"];
        let letter = document.getElementById("letter")!;
        let capital = document.getElementById("cap")!;
        let number = document.getElementById("num")!;
        let length = document.getElementById("len")!;

        // pwdInp.onfocus = () => {
        //     jq(".pwd-val").show();
        // };
        // pwdInp.onblur = () => {
        //     jq(".pwd-val").hide();
        // };
        const checkPass = () => {
            let lows = /[a-z]/g;
            if (pwdInp.value.match(lows)) {
                jq(letter).removeClass(invalidClass);
                jq(letter).addClass(validClass);
            } else {
                jq(letter).addClass(invalidClass);
                jq(letter).removeClass(validClass);
            }

            let caps = /[A-Z]/g;
            if (pwdInp.value.match(caps)) {
                jq(capital).removeClass(invalidClass);
                jq(capital).addClass(validClass);
            } else {
                jq(capital).addClass(invalidClass);
                jq(capital).removeClass(validClass);
            }

            let nums = /[0-9]/g;
            if (pwdInp.value.match(nums)) {
                jq(number).removeClass(invalidClass);
                jq(number).addClass(validClass);
            } else {
                jq(number).addClass(invalidClass);
                jq(number).removeClass(validClass);
            }

            if (pwdInp.value.length >= 8) {
                jq(length).removeClass(invalidClass);
                jq(length).addClass(validClass);
            } else {
                jq(length).addClass(invalidClass);
                jq(length).removeClass(validClass);
            }

            const pwdVal: string = pwdInp.value;
            const pwdValid =
                pwdVal.match(lows) &&
                pwdVal.match(caps) &&
                pwdVal.match(nums) &&
                pwdVal.length >= 8;
            btnDisabled = (!pwdValid);
            // if (pwdValid) jq(".pwd-val").hide();
        }
        checkPass()
        pwdInp.onkeyup = checkPass;
    })
</script>

<div class="flex items-center justify-center w-100p h-80vh">
    <TMeta title={`Signup - ${SITE}`}/>
    {#if step == 0}
    <div bind:this={formRef}><UForm onsubmit={submitForm}  id="su-form" autocomplete="off">
            <fieldset class="formset m-auto border-card border-1 p-4 pb-4">
            <legend class="text-primary"><TuLink to="/">{SITE}</TuLink></legend>
                <h2 class="text-cente my-3 fw-6">Sign up</h2>
                <UFormGroup label="Username">
                     
                        <UInput
                            type="text"
                            name="username"
                            required
                            class=""
                            placeholder="e.g. johndoe"
                        />
                </UFormGroup>
                <UFormGroup label="Email">
                    
                        <UInput
                            type="email"
                            name="email"
                            required
                            placeholder="e.g. johndoe@gmail.com"
                        />
                </UFormGroup>
                <UFormGroup label="Password">
                     <UInput
                                autocomplete="off"
                                type={passType}
                                id="pass"
                                name="password"
                                required
                                class="grow"
                                bind:value={pwd}
                                placeholder="Enter password..."
                                pattern={passPattern.source}
                                title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
                            >
                            {#snippet trailing()}
                            {#if passType == "password"}
                            <!-- svelte-ignore a11y_click_events_have_key_events -->
                            <!-- svelte-ignore a11y_no_static_element_interactions -->
                            <span
                                onclick={() => {
                                    passType = ("text");
                                }}
                                class="btn-none"
                                title="show password"
                            >
                                <i class="fi fi-rr-eye"></i>
                            </span>
                        {:else}
                            <!-- svelte-ignore a11y_click_events_have_key_events -->
                            <!-- svelte-ignore a11y_no_static_element_interactions -->
                            <span
                                class="btn-none"
                                onclick={() => {
                                    passType = ("password");
                                }}
                                title="hide password"
                            >
                                <i class="fi fi-rr-eye-crossed"></i>
                            </span>
                        {/if}
                            {/snippet}
                        </UInput>
                            
                        <div class="pwd-val form-group my-2 ml-2 text-center ">
                            <p class="fs-12">
                                Must contain{" "}
                                <span
                                    id="letter"
                                    class={`fw-5 ${invalidClass}`}
                                >
                                    a lowercase
                                </span>
                                ,{" "}
                                <span
                                    id="cap"
                                    class={`fw-5 ${invalidClass}`}
                                >
                                    an uppercase
                                </span>
                                ,{" "}
                                <span
                                    id="num"
                                    class={`fw-5 ${invalidClass}`}
                                >
                                    a number
                                </span>
                                , and{" "}
                                <span
                                    id="len"
                                    class={`fw-5 ${invalidClass}`}
                                >
                                    at least 8 characters
                                </span>
                            </p>
                       
                </UFormGroup>
                <div class="fs-14 mt-1 ml-1 text-center">
                    <TuLink
                        to="/auth/reset-password"
                        class="text-primary text-center"
                    >
                        Forgot password?
                    </TuLink>
                </div>
                {#if err?.length != 0} <div class="mt-2 ml-2 text-whit fs-12 text-center text-error"><p >{err?.replace("tuned:", "")}</p></div>{/if}
                <div class="mt-2 form-group ">
                    <UButton
                        type="submit"
                        disabled={btnDisabled}
                        id="su-btn"
                        class="su-btn btn-primary w-100p"
                    >
                        Sign up
                    </UButton>
                </div>
                <div class="form-group text-center mt-3 fs-14">
                    <p>
                        Already have an account?{" "}
                        <TuLink
                            to="/auth/login"
                            class="text-primary"
                        >
                            Login
                        </TuLink>
                    </p>
                </div>
            </fieldset>
        </UForm></div>
        
        {:else}
        <UForm onsubmit={submitOTP}>
            <fieldset class="formset m-auto border-card border-1 px-5 pb-5">
                <legend class="flex items-center gap-2"> <UButton onclick={()=>step += 1} type="button" class="mt-1"><i class="fi fi-br-arrow-left"></i></UButton> <div>{SITE} auth</div></legend>
                <p class="text-center fs-13 mb-3">
                    Enter the 4-digit PIN sent to{" "}
                    <span class="text-primary">
                        {formData.email}
                    </span>
                </p>
                <UFormGroup>
                    <UInput
                        type="text"
                        placeholder="Enter OTP"
                        maxlength={4}
                        minlength={4}
                        class="text-center"
                        value={formData.otp}
                        onchange={(e: any) => {
                            if (isNaN(e.target.value as any)) return;
                            formData = ({
                                ...formData,
                                otp: e.target.value,
                            });
                        }}
                    />
                </UFormGroup>
                {#if err?.length != 0}  <p class="mt-2 ml-2 text-error fs-12 text-center">{err?.replace("tuned:", "")}</p>{/if}
                <div class="my-2">
                    <UButton type="submit" disabled={formData.otp?.length < 4 || btnDisabled} class="w-100p btn btn-primary">
                        Submit
                    </UButton>
                </div>
            </fieldset>
        </UForm>
        {/if}
</div>

// pages/auth/signup/index.vue
<template>
    <div>
      <div class="p-3 form-container body">
        <Head>
          <TMeta
            title="Create account - TunedStreamz"
            keywords="login tunedstreamz, tunedstreamz login, tunedstreamz auth"
          />
  
          <Meta
            name="keywords"
            content="login tunedstreamz, tunedstreamz login, tunedstreamz auth"
          />
        </Head>
        <div class="m" v-if="isSuccessful">
            <fieldset class="formset m-auto">
            <legend>Signup successful!</legend>

            <h3 class="fs-18 color-white-2 text-center">Please use the verification link we've sent to your email to complete signing up.</h3>
            </fieldset>
        </div> 
        <form v-else
          ref="formRef"
          id="su-form"
          
          autocomplete="off"
        >
        <fieldset class="formset m-auto">
            <legend>Create account</legend>
         
          <div class="form-group mb-13">
            <label for="username">Username:</label>
            <input
              type="text"
              id="username"
              name="username"
              required
              class="form-control"
              placeholder="Enter your username..."
              min-length="3"
              autocomplete="off"
              autocorrect="off"
              value="tonnidiaz"
            />
          </div>
          <div class="form-group mb-13">
            <label for="email">Email:</label>
            <input
            id="email"
              type="email"
              name="email"
              required
              value="clickbait4587@gmail.com"
              class="form-control"
              placeholder="Enter your email address..."
            />
          </div>
          <div class="form-group mb-13">
            <label for="pass">Password:</label>
            <input
              auto-complete="off"
              :type="passType"
              id="pass"
              name="password"
              required
              value="Baseline@072"
              class="form-control"
              placeholder="Enter password..."
              pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
              title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
            />
            <div style="left: -8px" class="Addon">
              <span
                v-if="passType == 'password'"
                @click="setPassType('text')"
                class="btn-none"
                title="show password"
              >
                <i class="fad fa-eye-slash"></i>
              </span>
  
              <span
                v-else
                class="btn-none"
                @click="setPassType('password')"
                title="hide password"
              >
                <i class="fad fa-eye"></i>
              </span>
            </div>
          </div>
  
          <div class="pwd-val form-group mb-13 p-10 d-none">
            <p class="fs-15 fw-5 color-white-1">
              Password must contain the following:
            </p>
            <ul>
              <li style="list-style-type: disc">
                <p id="letter" class="text-danger">
                  A <span class="fw-6">lowercase </span>letter
                </p>
              </li>
              <li style="list-style-type: disc">
                <p id="cap" class="text-danger">
                  A <span class="fw-6">capital </span>letter
                </p>
              </li>
              <li style="list-style-type: disc">
                <p id="num" class="text-danger">
                  A <span class="fw-6">number </span>letter
                </p>
              </li>
              <li style="list-style-type: disc">
                <p id="len" class="text-danger">
                  A minimum of <span class="fw-6">8 characters </span>
                </p>
              </li>
            </ul>
          </div>
          <div class="form-group mb-13">
            <label for="conf-pass">Confirm password</label>
            <input
  
              autocomplete="off"
              type="password"
              id="conf-pass"
              name="conf-pass"
              required
              class="form-control"
              value="Baseline@072"
              placeholder="Confirm your password..."
            />
            <div class="mt-3 t-c error">
              <p class="fs-12 color-red">{{ err }}</p>
            </div>
          </div>
          <div class="form-group d-none form-check">
            <input
              class="form-check-input"
              type="checkbox"
              aria-checked="false"
              name="terms"
              id="terms"
            />
            <label for="terms">
              I have read and agreed to the
              <NuxtLink class="tb-link" to="/terms-of-service">
                Terms of service
              </NuxtLink>
              &
              <NuxtLink class="tb-link" to="/privacy-policy">
                Privacy policy
              </NuxtLink>
              .
            </label>
          </div>
          <div class="mt-4 form-group t-c mb-13">
            <button
              type="submit"
              :disabled="btnDisabled"
              id="su-btn"
              class="btn su-btn bg-card w-100p"
            >
              Sign up
            </button>
          </div>
          <div class="form-group mb-13 text-center">
            <p>
              Already have an account?
              <NuxtLink to="/auth/login">
                <a class="color-orange">Login</a>
              </NuxtLink>
            </p>
          </div>
          </fieldset>
        </form>
      </div>
    </div>
  </template>
<script setup lang="ts">
import { ref, onMounted } from "vue";
import $ from 'jquery'
import { post } from "../../../utils/api";

const isSuccessful = ref(false);
const formRef = ref<HTMLFormElement | null>(null)
    const passType = ref("password");
   function setPassType(val : string) {
      passType.value = val;
    }

    const btnDisabled = ref(true), setBtnDisabled = (v: boolean) => {btnDisabled.value = v}
const err = ref("");
function setErr(v: any){
      err.value = v
    }

    const router = useRouter();

onMounted(()=>{
    
    const form = formRef.value
    if (!form) return;
    let pass : HTMLInputElement = form.querySelector("#pass")!;
      let confPass = form.querySelector("#conf-pass")!;
      //let form = document.querySelector("#su-form");

      confPass.addEventListener("keyup", (e: any) => {
        if (e.target.value !== pass.value) {
          //console.log('Passwords do not match...');
         setBtnDisabled(true)
          $(".error p").text("Passwords do not match").css("color", "red");
        } else {
          setBtnDisabled(false)
          $(".error p").text("");
        }
      });

      form.addEventListener("submit", function (e) {
        e.preventDefault();

        
        try{
            setBtnDisabled(true)
            err.value = "";
            console.log("Signing up...")
        $("#su-btn").text("Signing up...");
        let password = form["password"].value;
        
        let username = form["username"].value;
        let email = form["email"].value;

        let fd = new FormData();
        fd.append("username", username);
        fd.append("password", password);
        fd.append("email", email);
        post("/auth/signup?method=custom", fd)
          .then((res) => {
            $(".inProgress").hide();
            err.value = "";
            $(".su-btn").text("Successful!");
            const { id } = res.data;
            console.log(id)
            setBtnDisabled(false)
           isSuccessful.value = true
          })
          .catch((er: any) => {
            $(".inProgress").hide();
            let error = er.response?.data?.message;
            console.log(er);
            console.log(er.response);
            $(".su-btn").text("Retry");

            if (error) {
              if (error === "Could not send email") {
                $(".error p").css("color", "red");
                err.value = "Something went wrong! Please try again later.";
                $(".su-btn").text("Retry");
              } else {
                $(".error p").css("color", "red");
                $(".error p").text(error);
                
                setErr(error);
                $(".err").show();
              }
            }
            setBtnDisabled(false)
          });}
          catch(e){
            console.log(e)
            setBtnDisabled(false)
            $("#su-btn").text("Error! Retry...");
          }
      });
      const pwdInp = form["password"];
        let letter = document.getElementById("letter")!;
        let capital = document.getElementById("cap")!;
        let number = document.getElementById("num")!;
        let length = document.getElementById("len")!;

        pwdInp.onfocus = () => {
          $(".pwd-val").removeClass("d-none");
        };
        pwdInp.onblur = () => {
          $(".pwd-val").addClass("d-none");
        };

        pwdInp.onkeyup = () => {
          let lows = /[a-z]/g;
          if (pwdInp.value.match(lows)) {
            $(letter).removeClass("text-danger");
            $(letter).addClass("text-success");
          } else {
            $(letter).addClass("text-danger");
            $(letter).removeClass("text-success");
          }

          let caps = /[A-Z]/g;
          if (pwdInp.value.match(caps)) {
            $(capital).removeClass("text-danger");
            $(capital).addClass("text-success");
          } else {
            $(capital).addClass("text-danger");
            $(capital).removeClass("text-success");
          }

          let nums = /[0-9]/g;
          if (pwdInp.value.match(nums)) {
            $(number).removeClass("text-danger");
            $(number).addClass("text-success");
          } else {
            $(number).addClass("text-danger");
            $(number).removeClass("text-success");
          }

          if (pwdInp.value.length >= 8) {
            $(length).removeClass("text-danger");
            $(length).addClass("text-success");
          } else {
            $(length).addClass("text-danger");
            $(length).removeClass("text-success");
          }

          if (pwdInp.value !== form["conf-pass"].value) {
            $("#su-btn").attr("disabled", 'true');
            $(".error p").text("Passwords do not match").css("color", "red");
          } else {
            setBtnDisabled(false)
            $(".error p").text("");
          }
        };
})
definePageMeta({
  layout: "nohead",
});
</script>
