// apps/tstreamz/apps/frontend/src/routes/watch/tv/[id]/+page.svelte
<script lang="ts">
    import { page } from "$app/stores";
    import DillaBanner from "@/components/DillaBanner.svelte";
    import FixedMovieCard from "@/components/FixedMovieCard.svelte";
    import TerraBanner from "@/components/TerraBanner.svelte";
    import TMeta from "@/components/TMeta.svelte";
    import TrailerBtn from "@/components/TrailerBtn.svelte";
    import WatchlistBtn from "@/components/WatchlistBtn.svelte";
    import { localApi } from "@/lib/api";

    import { imgUrl, ROOT, SITE } from "@/lib/constants";
    import { preventScroll } from "@/lib/funcs";
    import { handleErrs } from "@cmn/utils/funcs";
    import type { IObj } from "@cmn/utils/interfaces";
    import TuLink from "@repo/ui/components/TuLink.svelte";
    import UAccordion from "@repo/ui/components/UAccordion.svelte";
    import { onMount, untrack } from "svelte";

    const showFrame = true
    let {data} = $props()
    let meta = $state<any>(null),
        setMeta = (v: any) => (meta = v);
    let server = $state(0),
        setServer = (v: number) => (server = v);
    let tv = $derived<IObj | null>(data.tv);
    let frame: HTMLIFrameElement;

    let episodes = $state<any>(null),
        setEpisodes = (v: any) => (episodes = v);
    let epsReady = $state<any>(null),
        setEpsReady = (v: any) => (epsReady = v);
    let currEp = $state<any>(null),
        setCurrEp = (v: any) => (currEp = v);
    let sNum = $state<any>(null),
        setSNum = (v: any) => (sNum = v);

    let eNum = $state<any>(null),
        setENum = (v: any) => (eNum = v);

    let id = $derived($page.params.id);

    const servers = () => {
        const movieId = id;
        const s = query.s ?? "1",
            e = query.ep ?? "1";
        return [`https://www.2embed.cc/embedtv/${movieId}&s=${s}&e=${e}`];
    };
    const embedUrls = (i: number = 3) => {
        return servers()[i];
    };

    const getEps = async (id: any, s: string) => {
        const url = `/tv/${id}?s=${s}`;

        setEpsReady(false);
        try {
            const r = await localApi.get(url);
            const episodes = r.data;
            // console.log({episodes});
            if (typeof episodes == "object")
            return episodes;
        } catch (e) {
            handleErrs(e);
            setEpsReady(true);
           
        }
    };

    const getMeta = async (id: any) => {
        const url = `/meta/tv/${id}`;
        try{
           const { data } = await localApi.get(url);
        const { meta } = data;
        // console.log({meta});
        return meta; 
        }
        catch(e){
            handleErrs(e)
        }
    };

    const setupEps = async (s: any) => {
        // When season changes
        try {
            const eps = await getEps(id, s);
            if (eps)
            {setEpisodes(eps);
            setCurrEp(eps.episodes[0])};
            setEpsReady(true);
        } catch (e) {
            handleErrs(e);
        }
    };
    onMount(() => {
        // When show changes
        scrollToTheTop();

        setupMeta();
        setSNum(null);
        if (tv.value) {
            let { s, ep } = query;
            s = s ?? "1";
            ep = ep ?? "1";
            setSNum(s);
            setENum(ep);
        }
    });

 $effect(()=>{
        console.log({tv});
    })
    $effect(() => {
        // Watch episodes
        const val = episodes;
        if (!val) return
        untrack(() => {
            const { ep } = Object.fromEntries($page.url.searchParams);
            const e = ep ?? "1";
            const i = parseInt(`${e}`) - 1;
            if (val.episodes) setCurrEp(val.episodes[i]);
            setEpsReady(true);
        });
    });

    const scrollToTheTop = () => {
        const _top = document.querySelector(".the-top");
        _top?.scrollIntoView({ behavior: "smooth" });
    };

    let query = $derived(Object.fromEntries($page.url.searchParams));
   
    $effect(() => {
        // watch rpute.query
        const v = query;
        untrack(() => {
            scrollToTheTop();

            let { s, ep } = v;
            s = s || "1";
            ep = ep || "1";
            setSNum(s);
            setENum(ep);
            if (episodes?.episodes) {
                setCurrEp(episodes.episodes[parseInt(`${ep}`) - 1]);
            } else {
                setCurrEp(null);
            }
        });
    });

    const setupMeta = async () => {
        const mta = await getMeta(id);
        setMeta(mta);
    };

    $effect(() => {
        const val = sNum;
        untrack(() => {
            setupEps(val);
        });
    });

    
</script>

<div class="h-100p">
    <div style="height: 5px" class="the-top"></div>
    <div class="mt-1 relative h-100p">
        {#if tv}
            <TMeta
                url={ROOT + `/watch/tv/${tv?.id}`}
                keywords={`TunedBass, TunedStreamz, ${tv?.title}, Watch ${tv?.title} TunedStreamz`}
                src={imgUrl + tv?.poster_path}
                desc={tv?.overview}
                title={`Watch ${tv?.name} - ${SITE}`}
            />
        {/if}
        <div class="relative h-100p">
            {#if tv}
                <div>
                    <div class="title-cont d-none hidden">
                        <h1 class="fs-16 t-c fw-7">
                            You're watching
                            <span class="color-orange">{tv.name}</span>
                        </h1>
                    </div>
                    {#if false}
                        <select
                            bind:value={server}
                            name="server"
                            id="server"
                            class="form-control w-150 my-5"
                        >
                            {#each servers() as server, i}
                                <option value={i}>
                                    Server {i + 1}
                                </option>
                            {/each}
                        </select>
                    {/if}

                    <div
                        class="mb-4 video-frame d-flex ai-center jc-center sandes br-10"
                    >
                        <iframe
                            title="Tunedtreamz frame"
                            bind:this={frame}
                            width="100%"
                            height={500}
                            allowFullScreen
                            frameborder="0"
                            src={showFrame ? embedUrls(server) : ''}
                        ></iframe>
                    </div>

                    <div class="md:flex md:gap-3 sandes br-10 p-3">
                        <div
                            style="flex-shrink: 0"
                            class="w-225px h-280px pos-rel"
                        >
                            <img
                                alt="Movie  banner"
                                loading="lazy"
                                class="br-4"
                                width="100%"
                                height="auto"
                                src={imgUrl + tv?.poster_path}
                            />
                        </div>

                        <div class="movie-info mt-4">
                            <h1 class="title">{tv?.name}</h1>
                            <div class="mt-2">
                                <div class="flex items-center">
                                    <TrailerBtn isShow id={tv?.id} />
                                    &nbsp; &nbsp;
                                    <span class="rating color-yellow">
                                        <span>
                                            <i class="fi fi-ss-star"></i>
                                        </span>
                                        {tv?.vote_average}
                                    </span>
                                    &nbsp; &nbsp;
                                    <WatchlistBtn item={tv} isShow />
                                </div>
                                <p class="plot mt-3">{tv?.overview}</p>
                            </div>
                            {#if meta}
                                <div
                                    style="textoverflow: ellipsis; overflow: hidden"
                                    class="mt-2 meta grid sm:grid-cols-2 gap-2"
                                >
                                    <ul class="fs-14">
                                        <li>
                                            <p>
                                                <span class="key">Genre(s): </span>
                                                {#if tv?.genres}
                                                    {#each tv?.genres as it, i}
                                                        <span>
                                                            {#if i !== tv?.genres.length - 1}
                                                                <span
                                                                    ><TuLink
                                                                        class="text-secondary"
                                                                        to={`/tv/genre/${it.id}`}
                                                                    >
                                                                        {it.name}
                                                                    </TuLink>
                                                                    &nbsp; | &nbsp;</span
                                                                >
                                                            {:else}
                                                                <TuLink
                                                                    class="text-secondary"
                                                                    to={`/tv/genre/${it.id}`}
                                                                >
                                                                    {it.name}
                                                                </TuLink>
                                                            {/if}
                                                        </span>
                                                    {/each}
                                                {/if}
                                            </p>
                                        </li>

                                        <li>
                                            <p>
                                                <span class="key">Date: </span>
                                                {tv?.first_air_date.split(
                                                    "-"
                                                )[0]} -
                                                {tv?.last_air_date.split(
                                                    "-"
                                                )[0]}
                                            </p>
                                        </li>
                                    </ul>
                                    <ul class="col-md-7 col-lg-6">
                                        <li>
                                            <p>
                                                <span class="key">Status: </span>
                                                {tv?.status}
                                            </p>
                                        </li>
                                        <li>
                                            <p>
                                                <span class="key">Language(s): </span>
                                                {#each tv?.spoken_languages as it, i}
                                                    <span>
                                                        {#if i !== tv?.spoken_languages.length - 1}
                                                            <span
                                                                >{it.name}&nbsp;&#x2022;&nbsp;</span
                                                            >
                                                        {:else}
                                                            <span
                                                                >{it.name}</span
                                                            >
                                                        {/if}
                                                    </span>
                                                {/each}
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            {:else}
                            <div class="mt-4 w-100p">
                                <div class="w-100p h-100p _row jc-center">
                                    <span class="loading loading-bars loading-md"></span>
                                </div>
                            </div>
                            {/if}
                        </div>
                    </div>
                    <!-- 103 -->
                    <div class="mt-4">
                        <!--AD-->
                        <TerraBanner />
                    </div>
                    <!-- 167 -->
                    <div
                        class="mt- sandes br-10 pd-4 flex mb-2"
                    >
                        {#if epsReady}
                            {#if episodes}
                               <div class="w-100p">
                                {#if currEp}
                                    <div>
                                        <h5 class="fs-18 text-white">
                                            S{sNum}Ep{eNum}: &nbsp;{currEp.name}
                                        </h5>
                                        <div class="mt-2 mb-2">
                                            <p><span class="key">Date:</span> <span class="text-secondary"> {currEp.air_date}</span></p>
                                        </div>
                                        <p>
                                            {currEp.overview}
                                        </p>
                                    </div>
                                {:else}
                                    <div class="loading-div w-100p h-100p m-0">
                                        <span class="fs-30 flex ai-center mt-4">
                                            <i class="fi fi-rr-sad-tear"></i>
                                        </span>
                                    </div>
                                {/if}
                            </div> 
                            {:else}
                            <div class="loading-div w-100p h-100p m-0">
                                <span class="fs-30 flex ai-center mt-4">
                                    <i class="fi fi-rr-sad-tear"></i>
                                </span>
                            </div>
                            {/if}
                            
                        {:else}
                            <div class="loading-div">
                                <span class="loading loading-lg loading-bars"></span>
                            </div>
                        {/if}
                    </div>
                    <div
                        class="mt-13 sandes br-10 md:grid md:grid-cols-3 gap-2 mb-3 pd-5 pdb-10"
                        style="margin: 0"
                    >
                        <div class="col-span-1">
                            <UAccordion>
                                {#snippet label()}
                                    <h4 class="fw-6 text-white">{tv.seasons.length} Seasons</h4>
                                {/snippet}
                                {#snippet content()}
         

                                <div class="mt-2 flex wrap jistify-center">
                                    {#each tv?.seasons as season, i}
                                        <TuLink
                                            class={`col m-1 btn btn-sm btn-outline btn-neutral ${
                                                `${sNum}` === `${i + 1}`
                                                    ? "text-secondary"
                                                    : ""
                                            }`}
                                            to={`/watch/tv/${tv?.id}?s=${i + 1}&ep=1`}
                                            >Season {i + 1}</TuLink
                                        >
                                    {/each}
                                </div>
                                {/snippet}
                            </UAccordion>
                            
                        </div>
                        <div class="col-span-2">
                            <UAccordion>
                                {#snippet label()}
                                    <h4 class="fw-6 text-white">{episodes?.episodes?.length} Episodes</h4>
                                {/snippet}
                                {#snippet content()}
                                <div class="flex wrap">
                                    {#if epsReady}
                                        {#if episodes}
                                        {#each episodes?.episodes as ep, i}
                                            <TuLink
                                                title={ep.name}
                                                class={`col-md-3 m-1 w-nowrap btn btn-sm btn-outline btn-neutral  ${
                                                    eNum ===
                                                    `${ep.episode_number}`
                                                        ? "text-secondary"
                                                        : ""
                                                }`}
                                                to={`/watch/tv/${tv?.id}?s=${ep.season_number}&ep=${ep.episode_number}`}
                                            >
                                                Episode {i + 1} :
                                                {ep.name}</TuLink
                                            >
                                        {/each}
                                                {:else}
                                                <div class="loading-div w-100p h-100p m-0">
                                                    <span class="fs-30 flex ai-center mt-4">
                                                        <i class="fi fi-rr-sad-tear"></i>
                                                    </span>
                                                </div>
                                        {/if}
                                    {:else}
                                        <div class="loading-div">
                                            <span class="loading loading-bars"></span>
                                        </div>
                                    {/if}
                                </div>
                                {/snippet}
                            </UAccordion>
                     
                        </div>
                    </div>

                    <div class="mt-4">
                        <TerraBanner />
                    </div>
                    <div class="mt-4">
                        <h3 class="he">Similar Shows</h3>
                        <div style="padding-left: 15px" class="mt-13 os d-flex">
                            {#if meta}
                                <FixedMovieCard movies={meta.similar} isShow />
                            {:else}
                                <div class="loading-div">
                                    <span class="loading loading-lg loading-bars"></span>
                                </div>
                            {/if}
                        </div>
                    </div>
                </div>
            {:else}
                <div
                    ontouchmove={preventScroll}
                    onwheel={preventScroll}
                    class="flex items-center justify-center loda"
                >
                    <p class="fs-40">
                        <b><span class="loading loading-lg"></span></b>
                    </p>
                </div>
            {/if}
        </div>
    </div>
</div>

// pages/watch/tv/[id]/index.vue
<template>
    <div>
        <div style="height: 5px" class="the-top"></div>
        <TMeta
            v-if="tv"
            :url="root + `/watch/tv/${tv?.id}`"
            :keywords="`TunedBass, TunedStreamz, ${tv?.name}, Watch ${tv?.name} TunedStreamz`"
            :src="imgUrl + tv?.poster_path"
            :desc="tv?.overview"
            :title="`Watch ${tv?.name} S${$route.query.s ?? 1}E${
                $route.query.ep ?? 1
            } - TunedStreamz`"
        />
        <ClientOnly v-if="tv">
            <div>
                <select :value="server" @change="(e: any)=>{
                        setServer(e.target.value)
                    }" name="server" id="server" class="form-control w-150 my-5">
                        <option v-for="(server, i) in servers()" :value="i">
                            Server {{ i + 1 }}
                        </option>
                    </select>
                <div
                    style="margin-top: 10px"
                    class="mb-4 br-10 video-frame d-flex ai-center jc-center sandes"
                >
                    <iframe
                    title="Frame"
                        width="100%"
                        height="500"
                        scrolling="yes"
                        frameborder="0"
                        allowfullscreen
                        class="br-4"
                        id="frame"
                        :src="embedUrls(server)"
                
                    ></iframe>
                    <!--/*:src="`https://www.2embed.cc/embedtv/${tv.id}&s=${s}&e=${e}`"*/-->
                </div>

                <div class="mt-14 d-flex-md sandes p-3 br-10">
                    <div
                        class="m-auto w-250 pos-rel h-280"
                        style="flex-shrink: 0"
                    >
                        <span
                            style="
                                box-sizing: border-box;
                                display: block;
                                overflow: hidden;
                                width: initial;
                                height: initial;
                                background: none;
                                opacity: 1;
                                border: 0px;
                                margin: 0px;
                                padding: 0px;
                                position: absolute;
                                inset: 0px;
                            "
                        >
                            <img
                                alt="Banner"
                                class="br-4"
                                :src="imgUrl + tv?.poster_path"
                            />
                        </span>
                    </div>
                    <div class="movie-info mt-14">
                        <h1>{{ tv?.name }}</h1>
                        <div class="mt-2">
                            <div class="d-flex ai-center">
                                <div>
                                    <TrailerBtn :id="tv?.id" :isShow="true" />
                                </div>
                                &nbsp; &nbsp;<span class="rating color-yellow"
                                    ><span><i class="fas fa-star"></i> </span>
                                    {{ tv?.vote_average }}</span
                                >&nbsp; &nbsp;
                                <WatchlistBtn :item="tv" :isShow="true" />
                                <!--Watchlist button-->
                            </div>
                            <p class="plot mt-13">
                                {{ tv?.overview }}
                            </p>
                        </div>
                        <div class="meta row">
                            <ul class="col-md-7 col-lg-6">
                                <li>
                                    <p>
                                        <b>Genre(s): </b>
                                        <NuxtLink
                                            :key="i"
                                            v-if="tv?.genres"
                                            v-for="(it, i) in tv?.genres"
                                            :to="`/tv/genre/${it?.id}`"
                                        >
                                            <span
                                                v-if="
                                                    i != tv?.genres.length - 1
                                                "
                                            >
                                                <NuxtLink
                                                    :to="`/tv/genre/${it?.id}`"
                                                    class="link"
                                                >
                                                    {{ it.name }}
                                                </NuxtLink>
                                                &nbsp;|&nbsp;
                                            </span>
                                            <NuxtLink
                                                class="link"
                                                :to="`/tv/genre/${it?.id}`"
                                                v-else
                                            >
                                                {{ it.name }}
                                            </NuxtLink>
                                        </NuxtLink>
                                    </p>
                                </li>

                                <li>
                                    <p>
                                        <b>Date: </b>
                                        {{ tv?.first_air_date.split("-")[0] }} -
                                        {{ tv?.last_air_date.split("-")[0] }}
                                    </p>
                                </li>
                            </ul>
                            <ul class="col-md-7 col-lg-6">
                                <li>
                                    <p><b>Status: </b>{{ tv?.status }}</p>
                                </li>
                                <li>
                                    <p>
                                        <b>Language(s): </b>
                                        <span
                                            :key="i"
                                            v-for="(
                                                it, i
                                            ) in tv?.spoken_languages"
                                        >
                                            <span
                                                v-if="
                                                    i !==
                                                    tv?.spoken_languages
                                                        .length -
                                                        1
                                                "
                                                >{{
                                                    it.name
                                                }}&nbsp;&#x2022;&nbsp;</span
                                            >
                                            <span v-else>{{ it.name }}</span>
                                        </span>
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="mt-13 mb-3">
                    <DillaBanner />
                </div>
                <div class="mt-13 sandes br-10 p-2 row mb-3" style="margin: 0">
                    <div v-if="epsReady">
                        <div v-if="currEp">
                            <h5>
                                S{{ sNum }}Ep{{ eNum }}: &nbsp;{{ currEp.name }}
                            </h5>
                            <div class="mt-2 mb-2">
                                <p>Date: {{ currEp.air_date }}</p>
                            </div>
                            <p>
                                {{ currEp.overview }}
                            </p>
                        </div>

                        <div v-else class="loading-div">
                            <p class="fs-20">No data!</p>
                        </div>
                    </div>
                    <div v-else class="skel w-100p h-150">
                        <h5 class="skel-text">Episode name</h5>
                        <div class="mt-2 mb-2">
                            <p class="skel-text">Date: 0000-00-00</p>
                        </div>
                        <p class="skel-text">
                            Lorem ipsum dolor, sit amet consectetur adipisicing
                            elit.
                        </p>
                        <p class="skel-text">
                            Lorem ipsum dolor, sit amet consectetur adipisicing
                            elit.
                        </p>
                        <p class="skel-text">
                            Lorem ipsum dolor, sit amet consectetur adipisicing
                            elit.
                        </p>
                        <p class="skel-text">
                            Lorem ipsum dolor, sit amet consectetur adipisicing
                            elit.
                        </p>
                    </div>
                </div>
                <div
                    class="mt-13 sandes br-10 row mb-3 pd-5 pdb-10"
                    style="margin: 0"
                >
                    <div class="col-md-4">
                        <fieldset class="p-4 w-100p fieldset border-card no-el">
                            <legend>Seasons</legend>

                            <div class="mt-2 row">
                                <NuxtLink
                                    :key="i"
                                    v-for="(season, i) in tv?.seasons"
                                    :class="`col m-1 btn btn-sm btn-outline-dark ${
                                        `${sNum}` === `${i + 1}` ? 'active' : ''
                                    }`"
                                    :to="`/watch/tv/${tv?.id}?s=${i + 1}&ep=1`"
                                    >Season {{ i + 1 }}</NuxtLink
                                >
                            </div>
                        </fieldset>
                    </div>
                    <div class="col-md-8">
                        <fieldset class="p-4 fieldset no-el border-card">
                            <legend class="">Episodes</legend>
                            <div class="mt-2 row">
                                <NuxtLink
                                    :key="i"
                                    v-if="episodes"
                                    v-for="(ep, i) in episodes?.episodes"
                                    :title="ep.name"
                                    :class="`col-md-3 m-1 w-nowrap btn btn-sm btn-outline-dark  ${
                                        eNum === `${ep.episode_number}`
                                            ? 'active'
                                            : ''
                                    }`"
                                    :to="`/watch/tv/${tv?.id}?s=${ep.season_number}&amp;ep=${ep.episode_number}`"
                                >
                                    Episode {{ i + 1 }} :
                                    {{ ep.name }}</NuxtLink
                                >

                                <div class="loading-div" v-else>
                                    <span>Loading Episodes...</span>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>

                <div class="mt-14">
                    <TerraBanner />
                </div>
                <div class="mt-14">
                    <h3 class="he">Similar Shows</h3>
                    <div style="padding-left: 15px" class="mt-13 os d-flex">
                        <FixedMovieCard
                            :movies="meta.similar"
                            :isShow="true"
                            v-if="meta"
                        />
                        <div v-else class="loading-div">
                            <h5>Loading...</h5>
                        </div>
                    </div>
                </div>
            </div>
        </ClientOnly>

        <div
            v-else
            @touchmove="(e) => e.preventDefault()"
            @wheel="(e) => e.preventDefault()"
            class="d-flex ai-center jc-center loda"
        >
            <p class="fs-40"><b>Loading....</b></p>
        </div>
        <Hold />
    </div>
</template>

<script lang="ts" setup>
import { ref, onBeforeMount, watch, onMounted } from "vue";
import { imgUrl, root } from "../../../../utils/constants";
import TerraBanner from "../../../../components/sda/TerraBanner.vue";
import DillaBanner from "../../../../components/sda/DillaBanner.vue";
import axios from "axios";
const server = ref(0), setServer = (v: number)=> server.value = v;
const meta = ref<any>(null),
    setMeta = (v: any) => (meta.value = v);
const episodes = ref<any>(null),
    setEpisodes = (v: any) => (episodes.value = v);
const epsReady = ref<any>(null),
    setEpsReady = (v: any) => (epsReady.value = v);
const currEp = ref<any>(null),
    setCurrEp = (v: any) => (currEp.value = v);
const sNum = ref<any>(null),
    setSNum = (v: any) => (sNum.value = v);

const eNum = ref<any>(null),
    setENum = (v: any) => (eNum.value = v);
const tv = ref<any>(null);

const route = useRoute();
const id = ref(route.params.id);

const servers = () => {   
    const movieId = id.value;
    const s = route.query.s ?? "1",
        e = route.query.ep ?? "1";
    return [
              `https://multiembed.mov/directstream.php?video_id=${movieId}&tmdb=1&s=${s}&e=${e}`,
              `https://www.2embed.cc/embedtv/${movieId}&s=${s}&e=${e}`,
          
          ]}
const embedUrls = (i: number = 3) => {
  
    return servers()[i];
};

const getEps = async (id: any, s: string) => {
    const url = root + `/api/tv/${id}?s=${s}`;

    setEpsReady(false);
    try {
        const { data } = await axios.get(url);
        const episodes = data.data;
        return episodes;
    } catch (e) {
        console.log("ERRA: ", e);
        setEpsReady(true);
        throw e; /* createError({
        statusCode: 500,
        message: "Error fetching episodes"
    }) */
    }
};

const getMeta = async (id: any) => {
    const url = `/api/meta/tv/${id}`;

    const { data } = await axios.get(url);
    const { meta } = data;
    return meta;
};

/// Get the show
const { data, error, execute, refresh } = await useFetch<any>(
    "/api/watch/tv/" + id.value,
    {
        watch: [id],
    }
);

if (error.value) {
    throw createError({
        statusCode: error.value?.statusCode,
        statusMessage: error.value.statusMessage,
    });
}
tv.value = data.value.tv;

const setupEps = async (s: any) => {
    // When season changes
    try {
        const eps = await getEps(id.value, s);
        setEpisodes(eps);
        setCurrEp(eps.episodes[0]);
        setEpsReady(true);
    } catch (e) {
        console.log(e);
    }
};

watch(episodes, (val) => {
    const { ep } = route.query;
    const e = ep ?? "1";
    const i = parseInt(`${e}`) - 1;
    if (val.episodes) setCurrEp(val.episodes[i]);
    setEpsReady(true);
});

const scrollToTheTop = () => {
    const _top = document.querySelector(".the-top");
    _top?.scrollIntoView({ behavior: "smooth" });
};

watch(
    () => route.query,
    (v) => {
        scrollToTheTop();

        let { s, ep } = v;
        s = s ?? "1";
        ep = ep ?? "1";
        setSNum(s);
        setENum(ep);
        if (episodes.value.episodes) {
            setCurrEp(episodes.value.episodes[parseInt(`${ep}`) - 1]);
        } else {
            setCurrEp(null);
        }
    }
);

const setupMeta = async () => {
    const mta = await getMeta(id.value);
    setMeta(mta);
};
watch(sNum, (val) => {
    setupEps(val);
});

onBeforeMount(() => {
    // When show changes
    scrollToTheTop();

    setupMeta();
    setSNum(null);
    if (tv.value) {
        let { s, ep } = route.query;
        s = s ?? "1";
        ep = ep ?? "1";
        setSNum(s);
        setENum(ep);
    }
});
</script>
