// apps/ui-next/src/components/TuLink.tsx
import { AnchorHTMLAttributes } from "react";
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";

interface IProps extends AnchorHTMLAttributes<any> {
    to?: string;
    reload?: boolean;
    noactive?: boolean;
}
const TuLink = ({
    children,
    to,
    href,
    className,
    reload,
    noactive,
    ...props
}: IProps) => {
    const pathname = usePathname();

    const adfreeRoutes = ["/auth", "/me"];
    const _class = `tu-link text-${pathname == (to || href) && !noactive ? "primary" : ""} ${className || ""}`;
    const _href = to || href;
    return reload ||
        adfreeRoutes.find((el) => pathname.includes(el)) != undefined ? (
        <a href={_href} className={_class} {...props}></a>
    ) : (
        <Link href={_href} className={_class} {...props}></Link>
    );
};

export default TuLink;

// apps/ui-sv/src/components/TuLink.svelte
<script lang="ts">
    import { page } from "$app/stores";
    import type { HTMLAnchorAttributes } from "svelte/elements";

    interface IProps extends HTMLAnchorAttributes {
        to?: string;
        reload?: boolean;
        noactive?: boolean;
    }
    let {
        children,
        to,
        href,
        class: _class,
        reload,
        noactive,
        ...props
    }: IProps = $props();
    const adfreeRoutes = ["/auth", "/me"];
</script>

<a
    data-sveltekit-reload={reload ||
        adfreeRoutes.find((el) => $page.url.pathname.includes(el)) != undefined}
    class={`tu-link text-${$page.url.pathname == (to || href) && !noactive ? "primary" : ""} ${_class || ""}`}
    href={to || href}
    {...props}>{@render children?.()}</a
>
