// components/Footer.vue
<template>
  <div class="footer-basic">
    <footer>

      <div style="padding: 0 !important; margin: 0 !important;" class="_row gap-10">
        <span class="list-inline-item"><NuxtLink to="/">Home</NuxtLink></span>
        <span class="list-inline-item"><NuxtLink to="/contact">Contact us</NuxtLink></span>
        <span class="list-inline-item"><NuxtLink to="/about">About us</NuxtLink></span>
      </div>
    
      <h6 class="fw-6 mt-5">DISCLAIMER!</h6>
      <p class="for" >
        TunedStreamz does not host or claim to host any of the movies and tv
        shows on this website. We use legal means of embeding the content!
      </p>
        <p style="margin-bottom: 70px" class="copyright">TUNEDBASS © {{ new Date().getFullYear()}}</p>
    </footer>
  </div>
</template>

// apps/tstreamz/apps/frontend/src/components/Footer.svelte
<script>

    import { SITE, email } from "@/lib/constants";

</script>
<footer class="footer footer-center text-base-content p-4 mt-10px">
    <aside>
       
        <p><b>DISCLAIMER!!</b> {SITE} does not host or claim to host any of the movies and tv
            shows on this website. We use legal means of embeding the content!</p>
            <p id="contact" class="text-primary mt-2"><span class="top- relative fs-12"><i class="fi fi-br-envelope"></i></span>&nbsp;{email}</p>
      <p>Copyright © {new Date().getFullYear()} - All right reserved by {SITE}</p>
    </aside>
  </footer>
