// components/Genres.vue
<template>
    <div  class="genres">
      <section>
        <h3 class="color-white-2">Movies</h3>
        <hr/>
        <ul class="movies">
          <li :key="i" v-for="(it, i) in appStore.genres?.movies" v-if="appStore.genres">
            <NuxtLink class="nav-link" :to="`/movies/genre/${it.id}`">{{
              it.name
            }}</NuxtLink>
          </li>
        </ul> 
      </section>
      <section>
        <h3 class="color-white-2">TV Shows</h3>
        <hr/>
        <ul class="movies">
          <li :key="i" v-for="(it, i)  in appStore.genres?.shows" v-if="appStore.genres">
            <NuxtLink class="nav-link" :to="`/tv/genre/${it.id}`">{{
              it.name
            }}</NuxtLink>
          </li>
        </ul>
      </section>
    </div>
  </template>
  
  <script setup lang="ts">
import { useAppStore } from '@/stores/app';

  const appStore = useAppStore()
  </script>

// apps/tstreamz/apps/frontend/src/components/Genres.svelte
    {#if genres}
    <div  class="genres flex flex-col gap-4">
        <section>
          <h3 class="title mb-3">Movies</h3>
          <!-- <UDivider class="mt-2"/> -->
          <ul class="movies list-disc list">
              {#each genres?.movies as it, i}
                  <li>
              <TuLink class="nav-link" to={`/movies/genre/${it.id}`}><span class="fw-7 text-white">
                &#9675;
              </span>{
                it.name
              }</TuLink>
            </li>
              {/each}
            
          </ul> 
        </section>
        <section>
          <h3 class="title mb-3">TV Shows</h3>
          <!-- <UDivider class="mt-2"/> -->
          <ul class="movies list-disc list">
            {#each genres?.shows as it, i}
                 <li >
              <TuLink class="nav-link" to={`/tv/genre/${it.id}`}><span class="fw-7 text-white">
                &#9675;
              </span>{
                it.name
              }</TuLink>
            </li>
            {/each}
           
          </ul>
        </section>
      </div>
    {/if}
   
  
  <script  lang="ts">
    import { appStore as _appStore } from '@/stores/app.svelte';
    import TuLink from '@repo/ui/components/TuLink.svelte';
    import UDivider from '@repo/ui/components/UDivider.svelte';

    let {genres} = $derived(_appStore)
  </script>
