// components/TrailerBtn.vue
<template>
    <button
      @click="showTrailer(id)"
      title="Show trailer"
      :class="
        'pos-rel btn btn-sm ' + (className ? className : 'btn-outline-secondary')
      "
    >
      <span>
        <i class="fal fa-video"></i>
      </span>
      &nbsp; Trailer
    </button>
  </template>
  
  <script setup lang="ts">
  import axios from "axios";
import { useAppStore } from "@/stores/app";
  import $ from "jquery"

const appStore = useAppStore();

const props = defineProps({
    isShow: Boolean,
    id: {
        type: Number, required: true},
    className: String
})
function showTrailer(id: number) {
      appStore.setTrailerId(null);
      appStore.setTrailerErr(null);
      $(".trailer-container").addClass("active");
      const url = props.isShow
        ? "/api/trailer/tv/" + id
        : "/api/trailer/m/" + id;
      axios
        .get(url)
        .then((r) => {
          const { trailer } = r.data;

          if (trailer?.key) appStore.setTrailerId(trailer.key);
          else appStore.setTrailerErr(true);
        })
        .catch((e) => {
          console.log(e);
        });
    }
  </script>

// apps/tstreamz/apps/frontend/src/components/TrailerBtn.svelte
<script lang="ts">
    import { localApi } from "@/lib/api";
    import { setTrailerId, setTrailerErr } from "@/stores/app.svelte";
    import { handleErrs } from "@cmn/utils/funcs";
    import _$ from "jquery";

    const {
        isShow,
        id,
        className,
    }: { isShow?: boolean; id: number; className?: string } = $props();
    function showTrailer(id: number) {
        setTrailerId(null);
        setTrailerErr(null);
        _$(".trailer-container").addClass("active");
        const url = isShow ? "/trailer/tv/" + id : "/trailer/m/" + id;
        localApi
            .get(url)
            .then((r) => {
                const { trailer } = r.data;

                if (trailer?.key) setTrailerId(trailer.key);
                else setTrailerErr("true");
            })
            .catch((e) => {
                handleErrs(e);
            });
    }
</script>

<button
    onclick={() => showTrailer(id)}
    title="Show trailer"
    class={"pos-rel btn btn-sm btn-secondary items-center justify-center flex " +
        (className ? className : "btn-outline btn-secondary")}
>
    <span>
        <i class="fi fi-rr-film"></i>
    </span>
    <span>Trailer</span>
</button>
