// pages/auth/login.vue
<template>
    <div >
      <div class="form-container p-3">
        <TMeta
          title="Login - TunedStreamz"
          keywords="login tunedstreamz, tunedstreamz login, tunedstreamz auth"
        /> 

  
        <form
          @submit="login"
          autocomplete="off"
          class="auth=f "
          action=""
          method="POST"
        >
        <fieldset class="formset m-auto border-card">
            <legend>Login</legend>
          <input hidden autocomplete="off" />

          <div class="form-group mb-3">
            <label for="email">Email:</label>
            <input
              type="email"
              id="email"
              required
              class="form-control"
              name="email"
              placeholder="Email Address"
              autocomplete="off"
            />
          </div>
          <div class="form-group mb">
            <label for="pass">Password:</label>
  
            <input
              id="pass"
              type="password"
              required
              class="form-control"
              name="password"
              placeholder="Password"
              autocomplete="off"
            />
            <NuxtLink class="mt-4 mb-4 color-orange" to="/contact-us">
              Forgot password?
            </NuxtLink>
            <div class="err">
              <p>{{ err }}</p>
            </div>
          </div>
          <div class="t-c">
            <div class="form-group mt-3 mb-3">
              <button type="submit" id="li-btn" class="btn bg-card2 w-100p">
                {{ txt }}
              </button>
            </div>
            <div class="form-group mb-3 text-center">
              <div>or...</div>
              <NuxtLink class="color-orange" to="/auth/signup"
                >Create account
              </NuxtLink>
            </div>
          </div>  </fieldset>
        </form>
  
      </div>
    </div>
  </template>
  <script setup lang="ts">
import { ref } from "vue";
import { post } from "../../utils/api";
import $ from "jquery";

const txt = ref("Login");
const err = ref("");


const route = useRoute()
const router = useRouter()

function  login(e: any) {
      e.preventDefault();
      const redirect = route.query.red;

      const { email, password } = e.target;
      const fd = new FormData();
      fd.append("email", email.value);
      fd.append("password", password.value);
      $(".inProgress").show();
      txt.value = "Loging in...";
      post("/auth/login", fd)
        .then((res) => {
          $(".inProgress").hide();
          localStorage.setItem("tuned-token", res.data.token);
          //dispatch(setUser(res.data.user))

          ///console.log(res.data.user)
          let rd = "";
          if (redirect) {
            rd = redirect as string;
          }
          txt.value = "Success!";
          window.location.href = window.location.origin + rd;
        })
        .catch((er) => {
          $(".inProgress").hide();
          txt.value = "Retry";
          console.log(er);
          console.log(er.response);
          let error = er.response?.data?.message;
          console.log(error);
          if (error) err.value = error;
        });
    }

    definePageMeta({
  layout: "nohead",
});
</script>

// apps/tstreamz/apps/frontend/src/routes/auth/login/+page.svelte
<script lang="ts">
    import TMeta from "@/components/TMeta.svelte";

    import { localApi } from "@/lib/api";
    import { STORAGE_KEYS, SITE } from "@/lib/constants";
    import { setUser } from "@/stores/user.svelte";
    import type { IObj } from "@cmn/utils/interfaces";
    import { page } from "$app/stores";
    import TuLink from "@repo/ui/components/TuLink.svelte";
    import UButton from "@repo/ui/components/UButton.svelte";
    import UForm from "@repo/ui/components/UForm.svelte";
    import UFormGroup from "@repo/ui/components/UFormGroup.svelte";
    import UInput from "@repo/ui/components/UInput.svelte";
    import { handleErrs } from "@cmn/utils/funcs";
    import TuPassField from "@repo/ui/components/TuPassField.svelte";

    let btnDisabled = $state(false),
        setBtnDisabled = (v: boolean) => (btnDisabled = v);
    let passType = $state<"password" | "text">("password"),
        err = $state(""),
        setPassType = (v: typeof passType) => (passType = v),
        setErr = (v: string) => (err = v);

    let formState = $state<IObj>({});

    const submitForm = async (e: any) => {
        try {
            setErr("");

            const formData = formState;
            const res = await localApi.post("/auth/login", formData);
            setUser(res.data.user);
            localStorage.setItem(STORAGE_KEYS.authTkn, res.data.token);
            setTimeout(() => {
                setBtnDisabled(false);
            }, 1500);

            const red = $page.url.searchParams.get("red");
            location.href = red || "/";
        } catch (e: any) {
            handleErrs(e);
            console.log(e);
            const _err = e.response?.data?.message?.startsWith?.("tu:")
                ? e.response.data.message?.replace("tu:", "")
                : "Something went wrong";
            setErr(_err);
        }
    };
</script>

<div class="flex items-center justify-center h-100p">
    <TMeta title={`Login - ${SITE}`} />
    <div >
        <UForm state={formState} onsubmit={submitForm}>
            <fieldset class="formset m-auto border-card border-1 p-4 pb-4">
                <legend class="text-primary text-xl text-cente"
                    ><TuLink to="/">{SITE}</TuLink></legend
                >
                <h2 class="text-cente my-3 fw-6">Login</h2>
                <div class="w-100p flex flex-col gap-2">
                    <UFormGroup label="Email/Username">
                        <UInput
                            placeholder="Enter email or username..."
                            required
                            bind:value={formState.username}
                        />
                    </UFormGroup>
                    <UFormGroup label="Password">
                        <TuPassField showValidation={false} required bind:value={formState.password} placeholder="Enter password..."/>
                    </UFormGroup>
                    {#if err.length}
                        <div
                            class="ml-2 text-whit fs-12 text-center text-error"
                        >
                            <p>{err?.replace("tuned:", "")}</p>
                        </div>
                    {/if}
                    <div class="fs-12 mt-1 ml-1 text-center">
                        <TuLink
                            to="/auth/reset-password"
                            class="text-primary text-center"
                        >
                            Forgot password?
                        </TuLink>
                    </div>
                    <UFormGroup class="mt-1">
                        <UButton
                            disabled={!formState.username?.length ||
                                !formState.password?.length}
                            class="w-full btn-primary"
                            type="submit">Login</UButton
                        >
                    </UFormGroup>
                    <UFormGroup>
                        <p class="fs-14 text-center">
                            Or <TuLink class="text-primary" to="/auth/signup"
                                >Create account</TuLink
                            >
                        </p>
                    </UFormGroup>
                </div>
            </fieldset>
        </UForm>
    </div>
</div>
